### ISSUE TITLE
“doesn’t” word

### ISSUE THREAD

**Issue by Kissaki** [streetsidesoftware/cspell-dicts#102]
It looks like `doesn` [is in the powershell dictionary](https://github.com/streetsidesoftware/cspell-dicts/blob/master/packages/powershell/powershell.txt#L68), but not in a general English dictionary.

Should it be `doesn’t` and `doesn't`? Or is punctuation like that not supported and generally ignored, resulting in partial-words being added like `doesn`?

**Comment by Jason3S** [comment]
Thank you. I removed it.
