### ISSUE TITLE
"copywright" is not marked as misspelled in some files

### ISSUE THREAD

**Issue by itsmaxymoo** [streetsidesoftware/cspell-dicts#1037]
[This is the file in question, Line 27](https://github.com/itsmaxymoo/bc125at-perl/blob/master/driver-helper/bc125at-perl-driver-helper.c)

It appears "copywright" is not marked as misspelled in one source code file. It is normally marked as incorrect, but not in this particular file. A quick grep through this repository shows "copywright" doesn't exist anywhere, so I'm unsure if this is the correct repo for this issue.

This is occurring using the Visual Studio Code "Code Spell Checker" extension on Linux, with the following other extensions installed:

```
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.cpptools
njpwerner.autodocstring
streetsidesoftware.code-spell-checker
syler.sass-indented
twxs.cmake
```

In the file, cSpell lists the following dictionaries as active:

```
backwards-compatibility
aws
companies
cpp
cryptocurrencies
en_us
filetypes
fullstack
public-licenses
softwareTerms
```

**Comment by nschonni** [comment]
Do you have `allowCompoundWords` set to true https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell#cspelljson-sections? And does it get flagged if your run from the CLI instead of https://github.com/streetsidesoftware/vscode-spell-checker

**Comment by itsmaxymoo** [comment]
1. `allowCompoundWords` is **false**
2. It does **not** get flagged from the CLI. May this be a vscode specific issue?
3. I can confirm this issue persists across two devices now.

**Comment by Jason3S** [comment]
@itsmaxymoo,

If it happens in one type of file and not in others, then it is most likely an issue with `allowCompoundWords`. I'm guessing it is a Python file that has the issue.

Please try adding the following to your configuration

**`cspell.json`**
```json
{
    "languageSettings": [
        {
            "languageId": "*",
            "allowCompoundWords": false
        }
    ]
}
```

`"languageId": "*"` will match all file types. To match only Python files, use `"languageId": "python"`

**Comment by itsmaxymoo** [comment]
That appeared to fix it... This was a C file. It may be advantageous to blacklist "copywright"...

**Comment by Kurt-von-Laven** [comment]
Attempting to blacklist compound words seems Sisyphean to me. It sounds like a very high ratio of maintainer effort to value added, particularly given that compound words can be banned by a setting.

**Comment by Jason3S** [comment]
Fixed in new release.
