### ISSUE TITLE
Rust: String Escapes are being spell checked

### ISSUE THREAD

**Issue by ZhenyaUsenko** [streetsidesoftware/cspell-dicts#1065]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/76219110/166117705-58005342-997f-418f-a776-504509a456e4.png">

**Comment by Jason3S** [comment]
@ZhenyaUsenko,

I don't think the escape sequences were added to the Rust dictionary.

JavaScript has a similar escape sequence, see: [js-hex-escape](https://github.com/streetsidesoftware/cspell-dicts/blob/068dcb6ac9b0371e6a2c5931d75b411100325a00/dictionaries/typescript/cspell-ext.json#L20)

The following should work:

**`cspell.json`**
```json
    "languageSettings": [
        {
            "languageId": "rust",
            "ignoreRegExpList": ["js-hex-escape"]
        }
    ]
```

**VS Code**
```json
    "cSpell.languageSettings": [
        {
            "languageId": "rust",
            "ignoreRegExpList": ["js-hex-escape"]
        }
    ]
```

**Comment by ZhenyaUsenko** [comment]
@Jason3S It works, thank
