### ISSUE TITLE
'Kg', from the International System of Units, shouldn't  be forbidden

### ISSUE THREAD

**Issue by Jota-Ve** [streetsidesoftware/cspell-dicts#1080]
![image](https://user-images.githubusercontent.com/71910512/167875432-e33a33d1-e235-49a5-bf62-5ee3de1ea071.png)

Why is '**kg**' forbidden by default ? Yeah, i know I can add it to `"ignoreWords"`:

![image](https://user-images.githubusercontent.com/71910512/167874612-9c0f0d2b-49fa-4c91-8b5f-68c91fe5dd76.png)

But why is this forbidden by default, if it is an **_international standard_** for weigth units ?

**Comment by Jason3S** [comment]
@Jota-Ve,

Can you tell me which dictionaries you are using?

Please try 
```sh
npx cspell trace kg
```

It should tell you which dictionary is forbidding it.

**Comment by Jota-Ve** [comment]
@Jason3S Sorry, I didn't  get it where to run this line. It didn't work on my terminal.

I'm using the English and Brazillian Portuguese dictionaries:

![image](https://user-images.githubusercontent.com/71910512/167987185-6375dad8-61b5-415f-934f-e50a35fd66d5.png)
![image](https://user-images.githubusercontent.com/71910512/167987685-8fe2e2ed-d3a7-40a5-a1f1-018b0c7656cb.png)

**Comment by Jason3S** [comment]
@Jota-Ve 

I just checked. The Brazilian dictionary allows `kg` but explicitly forbids `Kg` and `KG`. That is the source of the issue.

**Comment by Jota-Ve** [comment]
@Jason3S 

Oh, alright. Is this the desired behaviour and I should close this issue, or it will be changed ? I've done some quick research and only found one site saying it should always be lowercase (``kg``, and **not** ``Kg`` or ``KG``). But I don't know if that's **really** the only grammatically right option. And, as a Brazillian, I certainly know people don't follow this _(speacially when the rest of the sentence is all uppercase)_.

**Comment by Jason3S** [comment]
@Jota-Ve,

The dictionary comes from [LibreOffice/dictionaries](https://github.com/LibreOffice/dictionaries). They would be the ones to bring up the `kg` vs `Kg` issue.

The most we can do on our side is add `Kg` and `KG` to an ignore list.
