### ISSUE TITLE
Publish Slovenian

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-dicts#1147]
Steps to Publish Slovenian Dictionary

- [x] Determine source of dictionaries
- [x] Add a copy of the license for `sl_SI.aff` and `sl_SI.dic`.
- [ ] Review Samples

**Comment by Jason3S** [comment]
@KrOstir,

> https://github.com/streetsidesoftware/cspell-dicts/pull/1144#issuecomment-1141059523

Are you able to answer the questions above?

Kind regards,
Jason

**Comment by KrOstir** [comment]
* [x]  Determine source of dictionaries

https://cgit.freedesktop.org/libreoffice/dictionaries/tree/sl_SI/

* [x]  Add a copy of the license for `sl_SI.aff` and `sl_SI.dic`.

https://cgit.freedesktop.org/libreoffice/dictionaries/tree/sl_SI/README_sl_SI.txt

The Slovenian spelling dictionary is covered by the GNU/LGPL and GNU/GPL License and supports Slovenian language (sl_SI).

* [ ]  Review Samples

I will make same cleaning in the file. Should I work on fork?

**Comment by Jason3S** [comment]
@KrOstir,

Thank you!

If you can make a PR to add [README_sl_SI.txt](https://cgit.freedesktop.org/libreoffice/dictionaries/tree/sl_SI/README_sl_SI.txt) to [dictionaries/sl_SI/src](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/sl_SI/src), that would be great. Otherwise, I'll try and take care of it tomorrow.

**Comment by KrOstir** [comment]
I have edited the README files, so if you just upload the README_sl_SI.txt everything should be OK.

**Comment by KrOstir** [comment]
> I have edited the README file, so if you just upload the README_sl_SI.txt

The `README_sl_SI.txt` has been uploaded in #1152.

**Comment by Jason3S** [comment]
> The README_sl_SI.txt has been uploaded in https://github.com/streetsidesoftware/cspell-dicts/pull/1152.

@KrOstir, Wonderful.

**Comment by Jason3S** [comment]
@KrOstir,

Published: [@cspell/dict-sl-si - npm](https://www.npmjs.com/package/@cspell/dict-sl-si)

**Comment by KrOstir** [comment]
> Published: [@cspell/dict-sl-si - npm](https://www.npmjs.com/package/@cspell/dict-sl-si)

Thanks, @Jason3S. I am moving now to VS Code Spelling Dictionary Extension 😄 .
