### ISSUE TITLE
Add "Cascadia" as a known word

### ISSUE THREAD

**Issue by ThomasMConnors** [streetsidesoftware/cspell-dicts#1193]
Add "Cascadia" as a known word either in the dictionary or at least as a known font. e.g.  "Cascadia Mono PL"

**Comment by Jason3S** [comment]
@ThomasMConnors,

Please feel free to add it to the [fonts list](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/fonts/fonts.txt). You can use the edit button to add your own words.

Suggested changes generally get added pretty quickly.

**Comment by ThomasMConnors** [comment]
Done. That was easy!

**Comment by Jason3S** [comment]
@ThomasMConnors,

Will you submit it as a Pull Request? I'll look it is when you are done.

**Comment by ThomasMConnors** [comment]
Done

**Comment by LucasOe** [comment]
Using the latest version of vscode-spell-checker (v2.20.5), "Cascadia" gets marked as an error for me, despite being in the dictionary.
