### ISSUE TITLE
Find a file for known names

### ISSUE THREAD

**Issue by rbalet** [streetsidesoftware/cspell-dicts#124]
I wanted to add those under the companies folder, but I'm not sure if they will fit there
they are : 
  - app name
  - tool names
  - website

```js    
    "unpkg",
    "reddit",
    "xbox",
    "whatsapp",
    "snapchat",
    "xing",
    "vimeo",
    "tumblr",
    "undraw",
    "crowdin",
    "docusaurus",
    "dayjs",
    "reactstrap"
```

Could maybe someone show me where and if I should add those

**Comment by Jason3S** [comment]
Things like `whatsapp` could go under company names. It was its own company.

There are some other dictionaries here: [cspell/packages/cspell-lib/dictionaries · streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell-lib/dictionaries)

**Comment by rbalet** [comment]
I add them to the companies directory since they didn't fit somewhere else. #125
