### ISSUE TITLE
add "guillemet" to EN dicts

### ISSUE THREAD

**Issue by revelt** [streetsidesoftware/cspell-dicts#1253]
let's add the word [guillemet](https://dictionary.cambridge.org/dictionary/english/guillemet) to all English dicts because it's the name of `« »` quotes

**Comment by Jason3S** [comment]
@revelt,

Please feel free add it to:
- [dictionaries/en_US/src/additional_words.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_US/src/additional_words.txt)
- [dictionaries/en_GB/src/additional_words.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_GB/src/additional_words.txt)

**Comment by revelt** [comment]
Thanks! I'll raise more if I find any.

**Comment by Jason3S** [comment]
@revelt,

Thank you.
