### ISSUE TITLE
Word contractions marked as spelling errors in Ada source code

### ISSUE THREAD

**Issue by brownts** [streetsidesoftware/cspell-dicts#1276]
## Info

**Kind of Issue**

- [x] runtime - command-line tools

## Bug Description

**Describe the bug**

When spell checking Ada source code, many word contractions are incorrectly marked as spelling mistakes.  This does not happen for other source code languages such as C.  I suspect this is due to the "ada word break" pattern in the Ada dictionary cspell-ext.json used to support language attributes (e.g., `Integer'Image(5)`).

**To Reproduce**

- test.adb
  ``` ada 
  with Ada.Text_IO;

  procedure Test is
  begin
    -- This didn't spell check properly.
    Ada.Text_IO.Put_Line(Integer'Image(5));
  end Test;
  ```
- test.c
  ``` c
  #include <stdio.h>

  int main (int argc, char* argv[])
  {
      /* This didn't spell check properly. */
      printf("%d\n", 5);
  }
  ```
- The following command line demonstrates the problem
  ```shell
  > npx cspell --version
  6.4.0
  > npx cspell --show-context --relative test.adb test.c
  1/2 ./test.adb 463.64ms X
  ./test.adb:3:11      - Unknown word (didn)       -- -- This didn't spell check properly
  2/2 ./test.c 202.04ms
  CSpell: Files checked: 2, Issues found: 1 in 1 files
  ```

**Expected behavior**

My expectation is that both source files should spell check correctly since they are using the same text in the comment block.  Only the Ada source file is flagged incorrectly as having a spelling mistake.

**Additional context**

This can be reproduced using the default cspell configuration.

**Comment by Jason3S** [comment]
@brownts,

This is caused by the fix to [Enhancement request: option to recognize apostrophe as a word boundary · Issue #531 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/issues/531).
