### ISSUE TITLE
Misspelled word not recognized

### ISSUE THREAD

**Issue by ari-wwu** [streetsidesoftware/cspell-dicts#1294]
I have a similar issue as described in [issue 1097](https://github.com/streetsidesoftware/cspell-dicts/issues/1097) -- the misspelled word "squentially" is not highlighted by the checker. I tried to follow the steps mentioned in issue 1097, but no entry in the regexp view highlights the misspelled word. Any help is appreciated!

**Comment by Jason3S** [comment]
@ari-wwu,

Are you able to give an example that demonstrates the issue? There isn't enough information to go on.

**Comment by Jason3S** [comment]
@ari-wwu,

Are you using VS Code?

There are some limits set in the extension.
1. File size limit
   <img width="355" alt="image" src="https://user-images.githubusercontent.com/3740137/180803589-eb1fbcc1-5dce-4b98-9f51-229053bfe83c.png">
 
1. Max number of issues.
   <img width="457" alt="image" src="https://user-images.githubusercontent.com/3740137/180803320-7dbeb6fe-25f0-4400-a270-5fc8f6c9df32.png">

**Comment by ari-wwu** [comment]
That was the issue -- many thanks!
