### ISSUE TITLE
Add ignores for LaTex

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-dicts#13]
See: https://github.com/Jason-Rev/vscode-spell-checker/issues/125

**Comment by galgalesh** [comment]
Hi @Jason3S 

There are a number of Latex keywords missing. Is there a way for me to add them to Code Spell Checker? Is the dictionary in this repo automatically included in Code Spell Checker? Can I create a PR to include the keywords?

**Comment by Jason3S** [comment]
Please do. They will get pulled into the VS Code Spell Checker on the next release.

**Comment by tobiasdiez** [comment]
I think this can be closed (at least there exist https://github.com/streetsidesoftware/cspell-dicts/tree/master/packages/latex).
