### ISSUE TITLE
Arabic: Support Harakat

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-dicts#1314]
As mentioned the link to improve the dictionary in this [link](https://github.com/streetsidesoftware/cspell/issues/2249#issuecomment-1031165944)

we have a problem in [Harakat in Arabic](https://github.com/streetsidesoftware/cspell/issues/2249#issuecomment-1031182816). They are considered complete letters. How we can ignore them?

![Screen Shot 2022-07-29 at 11 43 43](https://user-images.githubusercontent.com/24838274/181720877-3a19a87b-803a-4bf2-957e-c5d6a6c1955f.png)

_Originally posted by @WatheqAlshowaiter in https://github.com/streetsidesoftware/cspell-dicts/issues/941#issuecomment-1199028689_

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

Great example. Would you please add (in text) some example word pairs?

It is possible words with Harakat are not in the dictionary, you might need to follow up with @linuxscout to see if they are there. I'll regenerate the dictionary to a greater depth see if those words are added. But he might have a better idea on how Harakat is handled in other spell checkers.

**Comment by linuxscout** [comment]
ٍHi @Jason3S,
To resolve this issue, we must remove diacritics before spellchecking,
we add remove_diacritics(word).

The word to compare against the dictionary is a non diacritized word (word without diacritics).
This case is handled by Hunspell like this, we added a feature name "IGNORE"  to ignore a list of diacritics in the word. In the code we remove diacritics before spelling, but  we keep it on display.

**Comment by linuxscout** [comment]
@Jason3S  No need to rebuild the dictionary

**Comment by Jason3S** [comment]
@linuxscout,

Thank you.

Found it:
![image](https://user-images.githubusercontent.com/3740137/181737122-54ef6d9b-5052-4ab3-aa74-b92daae9e917.png)

I'll see if I can add support for `IGNORE` to `cspell`.

**Comment by Jason3S** [comment]
I have added support to CSpell to ignore accents if specified in the dictionary definition.

I'll update the VS Code extension tomorrow.
