### ISSUE TITLE
"wont" should probably be an error

### ISSUE THREAD

**Issue by Nightblade** [streetsidesoftware/cspell-dicts#1466]
"wont" is currently considered correct by four dictionaries according to the `trace` I just ran (see below).

I think most occurrences of "wont" are going to be misspellings of "won't", especially in code.  "Wont" has a different meaning than "won't", is rarely used, and is generally considered to be an archaic word.

&nbsp;
```
Word F Dictionary           Dictionary Location           
wont * cpp                  C:\Progs\Nodist\bin\node_modules\cspell\node_modules\@cspell\dict-cpp\cpp.txt.gz
wont * en_us*               C:\Progs\Nodist\bin\node_modules\cspell\node_modules\@cspell\dict-en_us\en_US.trie.gz
wont * en-gb*               C:\Progs\Nodist\bin\node_modules\cspell\node_modules\@cspell\dict-en-gb\en_GB.trie.gz
wont * python               C:\Progs\Nodist\bin\node_modules\cspell\node_modules\@cspell\dict-python\python.txt.gz
```

**Comment by Jason3S** [comment]
@Nightblade,

I believe that the `python` and `cpp` are incorrect.

The difficult part is what to do about very rare words that are commonly misused in place of a common word. `wont` vs `won't` is a perfect example.

My proposal is to create a `typos` dictionary for these mistakes.

It would be included by default to flag issues that you have pointed out, but could be easily turned off by those who want to "full" English language.

**Comment by Nightblade** [comment]
Hi @Jason3S,

Your proposal sounds good.

As a general rule I think software should always default to "make noise" rather than "silently continue" when there is sufficient doubt.   `Wont` is a good example:  I would never have even known it was there in the code if I hadn't specifically searched for it, and 99% of the time it's a misspelling.

**Comment by calvinballing** [comment]
Would the `typos` or `common-typos` dictionary just reuse the existing forbidden words mechanism?

**Comment by Jason3S** [comment]
@calvinballing,

Here is an RFC exploring the issue: [cspell/rfc/rfc-0001 suggestions](https://github.com/streetsidesoftware/cspell/tree/v6.13.1/rfc/rfc-0001%20suggestions)
