### ISSUE TITLE
`&middot;` HTML entity not in HTML dict

### ISSUE THREAD

**Issue by alystair** [streetsidesoftware/cspell-dicts#156]
`&middot;` being is not recognized, it's a common html entity.

https://www.toptal.com/designers/htmlarrows/punctuation/middle-dot/

**Comment by Jason3S** [comment]
I believe this is now fixed:
`&middot;` is part of [html-symbol-entities](https://github.com/streetsidesoftware/cspell-dicts/blob/master/dictionaries/html-symbol-entities/entities.txt#L569)
