### ISSUE TITLE
Gaming Dictionary 

### ISSUE THREAD

**Issue by KieranRobson** [streetsidesoftware/cspell-dicts#1591]
For times like:
Headshot 
Deathmatch 
Unranked 

Basically, for when words are compressed for gaming situations. Im happy to populate it if the dictionary is created!

**Comment by Jason3S** [comment]
@KieranRobson,

Looks like the `create-dictionary` script had gotten broken. I have fixed it with #1603.

Please try:

`yarn create-dictionary gaming-terms` from the repository root. Most of the prompts should be clear.

**Comment by KieranRobson** [comment]
Will give it ago when Im available!
