### ISSUE TITLE
POSIX shell

### ISSUE THREAD

**Issue by carlocorradini** [streetsidesoftware/cspell-dicts#1612]
Currently, there is only a `bash` dictionary that includes both `POSIX shell` and `Bash` words.
However, this can create issues when dealing with "pure" `POSIX` script files (e.g., `#!/usr/bin/env sh`).
I propose to create a `POSIX sh` (or `POSIX shell` or simply `sh`) dictionary that contains only valid `POSIX` shell words without any _bashism_.
The `bash` dictionary simply extends the `POSIX` shell dictionary with `bash` definitions (e.g., `BASH_SOURCE`).
Moreover, in the future, this simplifies the addition of new shells (e.g., `zsh` or `fish`) since they all rely on the base `POSIX` shell dictionary.

What do you think?

**Comment by Jason3S** [comment]
@carlocorradini,

I think it is fine to separate out the terms into their own files.

There are two basic options:
1. Publish a single package `cspell-shell-scripts` that contains the various dictionaries.
2. Publish each dictionary separately (each one in its own npm package).

My leaning is towards `1` since these are very small dictionaries. The challenge is how to detect which dictionary to use. At the moment, CSpell only uses the name of the file.

**Comment by carlocorradini** [comment]
Agree on 1.
Maybe we can check if the file has a '.sh' (note that script could also have no extension) and check shebang (only first line of the file)?

**Comment by Jason3S** [comment]
By default CSpell looks at the extension / filename to determine the file type.
See for definitions: https://github.com/streetsidesoftware/cspell/blob/main/packages/cspell-lib/src/LanguageIds.ts

Example: `{ id: 'dockerfile', extensions: ['.dockerfile'], filenames: ['Dockerfile'] },`
It will use "dockerfile" if the extension is `.dockerfile` or the filename is `Dockerfile`.

It is also possible to setup glob rules to match certain paths, like `**/.ssh/config`.

But it doesn't currently look at the content of the file to determine the type, but that is a viable enhancement.

**Comment by carlocorradini** [comment]
I see... I think the feature of looking for something into the file could be very useful not only for this purpose but also in the future.
I could try to build something that try to search for a pattern in the file but I need some help.
Moreover how can this be reflected in the definitions (e.g.):
```ts
export const languageExtensionDefinitions: LanguageDefinitions = [
  // ...
  {
    id: 'shellscript',
    extensions: [ // ... ],
    kinds: [
      {
        id: 'bash',
        extensions: [ '.sh', '.bash', '.bashrc', // ... ],
        contents: [ '#!/usr/bin/env bash', '#!/bin/bash' ]
      },
      {
        // ...
      }
    ]
  }
];
```

**Comment by nschonni** [comment]
I'm thinking a spell check isn't the best way to enforce a shell dialect in a file though. As you mentioned above, there are tools like `shellcheck` that are more built for that

**Comment by carlocorradini** [comment]
@nschonni True
Therefore, the only thing I propose to @Jason3S is to deprecate/rename the `bash` dictionary and create a new one called `shell` or `sh` where we put all the words for all known shells (`POSIX`,`bash`,`zsh`,`fish`,etc...)

**Comment by carlocorradini** [comment]
The words must be separated in different files:
**POSIX-words.txt**
```txt
echo
command
...
```
**bash-words.txt**
```txt
BASH_ARGV0
BASH_COMPAT
BASH_SOURCE
BASH_XTRACEFD
BASHOPTS
...
```

@Jason3S a dictionary can have multiple .txt file?

**Comment by Jason3S** [comment]
@carlocorradini,

Options:
- A single package can contain multiple dictionaries. See: [Software Terms](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/cspell-ext.json)
- A single dictionary can be built from multiple files. See: [English US](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_US/source-files.txt)

**Comment by carlocorradini** [comment]
@Jason3S What do you think is better? \
*Single dictionary, multiple files*?

**Comment by Jason3S** [comment]
@carlocorradini,

A single dictionary and multiple sources is fine. If you can split the existing Bash source file, I'll take care of renaming the dictionary.

To do:
- [ ] - @carlocorradini - split [bash-words](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/bash/src/bash-words.txt) into different files.
- [ ] - @Jason3S - setup multi-source configuration.
- [ ] - @Jason3S - rename dictionary and packages.

**Comment by carlocorradini** [comment]
@Jason3S 

Here you go 🥳

Note that each `*-words.txt` has been sorted alphabetically

# **Shells**
## **shell-sh-words.txt**
```txt
alias 
allexport 
bg 
bind 
break 
case 
cd 
command 
continue 
do 
done 
echo 
elif 
else 
errexit 
esac 
eval 
exec 
exit 
export 
false 
fc 
fg 
fi 
getopts 
hash 
help 
history 
if 
ignoreeof 
in 
jobs 
kill 
logout 
monitor 
noclobber 
noexec 
noglob 
nolog 
notify 
nounset 
printf 
pwd 
read 
return 
set 
shift 
test 
then 
times 
trap 
true 
type 
ulimit 
umask 
unalias 
unset 
until 
verbose 
wait 
while
```

## **shell-bash-words.txt**
```txt
braceexpand 
builtin 
caller 
compgen 
complete 
compopt 
declare 
dirs 
disown 
enable 
errtrace 
for 
function 
functrace 
globstar 
hashall 
histexpand 
let 
local 
mapfile 
onecmd 
pipefail 
popd 
pushd 
readarray 
readonly 
select 
shopt 
source 
suspend 
typeset
```


## **shell-zsh-words.txt**
```txt
coproc
```

# **Commands**
## **command-words.txt**
```txt
dbus 
dpkg 
emacs 
mkdir 
newgidmap 
newuidmap 
notify 
nvim 
proxyd 
readlink 
shellcheck 
shfmt 
time 
tput 
uidmap 
vi 
vim 
xtrace
```

# **Miscellaneous**
## **miscellaneous-words.txt**
```txt
autoremove 
dearmor 
enarmor 
history 
inlib 
keyrings 
keyword 
physical 
posix 
privileged
```

# **Global Variables**
## **glob-words.txt**
```txt
BASH_ARGV0 
BASH_COMPAT 
BASH_SOURCE 
BASH_XTRACEFD 
BASHOPTS 
CHILD_MAX 
COLUMNS 
COMP_WORDBREAKS 
COMPREPLY 
EUID 
EXECIGNORE 
FUNCNAME 
FUNCNEST 
GLOBIGNORE 
HISTCONTROL 
HISTFILE 
HISTFILESIZE 
HISTIGNORE 
HISTSIZE 
HISTTIMEFORMAT 
HOME 
HOSTFILE 
HOSTNAME 
HOSTTYPE 
IFS 
LANG 
LC_ALL 
LC_COLLATE 
LC_CTYPE 
LC_MESSAGES 
LC_NUMERIC 
LC_TIME 
LINES 
MACHTYPE 
MAIL 
MAILCHECK 
MAILPATH 
OLDPWD 
OPTERR 
OPTIND 
OSTYPE 
PATH 
PIPESTATUS 
POSIX_PEDANTIC 
POSIXLY_CORRECT 
PPID 
PROMPT_COMMAND 
PS1 
PS2 
PS3 
PS4 
READLINE_LINE 
READLINE_MARK 
READLINE_POINT 
SCRIPTDIR 
SECONDS 
SHELL 
SHELLOPTS 
SSH2_CLIENT 
SSH_CLIENT 
TERM 
TERMCAP 
TERMINFO 
TEXTDOMAIN 
TEXTDOMAINDIR 
TMOUT 
TZ 
UID
```

**Comment by Jason3S** [comment]
@carlocorradini,

Is it possible to make it a PR and just add them here: https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/bash/src ?

**Comment by carlocorradini** [comment]
@Jason3S 
Check PR #1635 
Note that you must delete the old `bash-words.txt` from both `src` and `dict`

**Comment by Jason3S** [comment]
@carlocorradini,

PR #1639 contains your changes.

- `cspell.config.yaml` is used to define how to build the dictionaries.
- `cspell-ext.json` is how `cspell` knows about the dictionaries.

**Comment by carlocorradini** [comment]
Can we close this?
