### ISSUE TITLE
K8s dictionary

### ISSUE THREAD

**Issue by carlocorradini** [streetsidesoftware/cspell-dicts#1688]
K8s dictionary

**Comment by Jason3S** [comment]
@carlocorradini,

Please feel free to [Create a K8 Dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary) and submit a Pull-Request.

**Comment by carlocorradini** [comment]
Can we use https://github.com/instrumenta/kubernetes-json-schema and extract the words with some script?
What do you think?

**Comment by carlocorradini** [comment]
Working on it

**Comment by carlocorradini** [comment]
@Jason3S See #1704 

Please check and add your review
