### ISSUE TITLE
Gaming Terms Not Available

### ISSUE THREAD

**Issue by KieranRobson** [streetsidesoftware/cspell-dicts#1695]
```
unban - fullstack*           ..\..\..\..\AppData\Roaming\npm\node_modules\cspell\node_modules\@cspell\dict-fullstack\fullstack.txt.gz 
unban - golang               ..\..\..\..\AppData\Roaming\npm\node_modules\cspell\node_modules\@cspell\dict-golang\dict\go.txt
unban - haskell              ..\..\..\..\AppData\Roaming\npm\node_modules\cspell\node_modules\@cspell\dict-haskell\dict\haskell.txt  
```

The gaming dict seemed to not have been built or available, this may have been my doing when I created it 😆 

Using `cspell@16.7.0`

**Comment by Jason3S** [comment]
Or you can just add it to your project:

```
npm i -SD @cspell/dict-gaming-terms
```

**`cspell.json`**
```json
{
  "import": ["@cspell/dict-gaming-terms/cspell-ext.json"],
  "dictionaries": ["gaming-terms"]
}
```

**Comment by KieranRobson** [comment]
Hmm, Still no luck 

Here is the [repo](https://github.com/KieranRobson/Clarence-Bot) with the [.cspell.json file](https://github.com/KieranRobson/Clarence-Bot/blob/master/.cspell.json) and [config file](https://github.com/KieranRobson/Clarence-Bot/blob/master/cspell-default.config.js)

**Comment by Jason3S** [comment]
@KieranRobson,

I'm sorry about that. I had forgotten to make it public so it would be published.

I'll publish it today.
