### ISSUE TITLE
Add - companies : facebook & instagram

### ISSUE THREAD

**Issue by rbalet** [streetsidesoftware/cspell-dicts#1700]
`facebook` and `instagram` are wrong, but `twitter`, `youTube` and `linkedIn` are correct.

When coding, words are `camelCase`, so `facebook` stay lower case

Shall I add them in the companies dict. ?  Will do if they will get accepted

**Comment by rbalet** [comment]
@Jason3S 
Funnily Enough It's correct in ts file but not in html one
|TYPESCRIPT|HTML|
|---|---|
|![image](https://user-images.githubusercontent.com/44493964/207249573-46bdb7b2-a005-4853-8ce0-ac40c9587dcd.png)|![image](https://user-images.githubusercontent.com/44493964/207249415-9ed431d2-9ff4-4488-9e1a-c8a7b5fad562.png)|

**Comment by Jason3S** [comment]
@rbalet,

The reason you are seeing a difference is that in some file types, `caseSensitive` is turned off.

`caseSensitive` is really "case and accent sensitive". For code, being case sensitive doesn't make a lot of sense. But for documents and things shown on web pages, getting it right can be important.

This is especially true for accent rich languages like French, Spanish, and Portuguese in addition to case sensitive languages like German.

Facebook is a special case, it is both a company and the name of an API. It might be worth adding the lowercase version to the "fullstack" dictionary.

**Comment by rbalet** [comment]
@Jason3S Ok, I'm closing this issue in favor of the pull request I did
