### ISSUE TITLE
Bundled-Dicts Updated With CSpell-Dicts

### ISSUE THREAD

**Issue by KieranRobson** [streetsidesoftware/cspell-dicts#1743]
Is there a way for [`@https://www.npmjs.com/package/@cspell/cspell-bundled-dicts`](https://www.npmjs.com/package/@cspell/cspell-bundled-dicts?activeTab=explore) to be updated when any of the cspell-dicts gets updated?

Even if a contributor could update it through a PR? 😆 

No worries if itd be too much work!

**Comment by Jason3S** [comment]
@KieranRobson,

Most updates happen automatically. There is a nightly workflow that updates the dictionaries.

It does look like the README.md is a bit out of date.

A PR is always welcome.

**Comment by KieranRobson** [comment]
I believe its a release that needs to occur to update the package through npm? I could be wrong

When doing yarn add, it has the release that was 8 days ago rather than any of the new words such as the ones added to the gaming dict and npm

I may be setting it up wrong though

I'll have a look at the docs when I'm free!

**Comment by Jason3S** [comment]
I can release `cspell` again. It hasn't been published in a week.

**Comment by Jason3S** [comment]
@KieranRobson,

Are you expecting `gaming-terms` and they are not showing up?

They are bundled, but not enabled by default. 

The dictionary has to be enabled:

**`cspell.config.yaml`**
```yaml
dictionaries:
  - gaming-terms
```

**Comment by KieranRobson** [comment]
Gaming terms works, but the new updated 1.03 isn't accessible unless there is a new release of cspell

**Comment by Jason3S** [comment]
@KieranRobson,

That is a `yarn` issue. I think you need to use `yarn up` or `yarn upgrade` depending upon your version. `cspell` uses `^` for version matching on the dictionaries so that they can be updated without needing to release a new version of `cspell`.

**Comment by KieranRobson** [comment]
Oh! I can give it ago when the 8.0.0 is pushed with the dict changes! Thanks!

Im still learning `yarn` and dependency management haha

**Comment by KieranRobson** [comment]
`yarn upgrade` fixed this
