### ISSUE TITLE
Small additions to software terms dictionary

### ISSUE THREAD

**Issue by lee0c** [streetsidesoftware/cspell-dicts#1824]
The softwareTerms dictionary has 

- ['idempotent'](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/software-terms.txt#L604). It could also include 'idempotence'.
- ['toolchain'](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/software-terms.txt#L1402). It could also include 'toolchains'.

I can PR this if that's easier for you.

**Comment by Jason3S** [comment]
@lee0c,

Please fee free to make a PR. You can edit the file in the browser: [software-terms.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/software-terms.txt).

**Comment by lee0c** [comment]
@Jason3S Opened, [PR here](https://github.com/streetsidesoftware/cspell-dicts/pull/1829)
