### ISSUE TITLE
French spell checker: add "nœud" as a possible fix to "noeud"

### ISSUE THREAD

**Issue by Questionsdenombres** [streetsidesoftware/cspell-dicts#1840]
# Technical Context
I am using:
- "Code Spell Checker" (v2.14.0)
- "French Code Spell Checker" (v0.2.4) ...
-  ... extensions to VSCode (1.74.3).

# Language Context
Some french words have [ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)) such as "[sœur](https://fr.wikipedia.org/wiki/S%C5%93ur)" (sister) or "nœud" (node).

# Current behaviour
- cspell reports as errors the words without the ligatures, namely: "soeur" or "noeud".
- The "quick fix menu" that appears in VSCode to select a replacement word doesn't include the word with the ligature.
- However when you enter it manually ("sœur"), then cspell doesn't report any error.

# Expected behaviour
I have no religion on this point and the possible solutions are:
1/ liberal: accept both "sœur" and "soeur" as valid.
2/ rigorist: only accept "sœur".

Currently cspell seems rigorist, but it doesn't suggest "sœur" as a possible fix to "soeur".

Actually the reason why I report the issue is that the "œ"-character is not easily accessible on any keyboard, and the usual way to get the correct spell is to accept a proposed fix from the tool. But here cspell doesn't propose the correct one.

Thank you for your great tool.

**Comment by Jason3S** [comment]
@Questionsdenombres and @nschonni,

Please see the discussion here (https://github.com/streetsidesoftware/cspell-dicts/issues/1703#issuecomment-1381541163) on how to improve Basque. The same thing could be applied to French.

```json
        {
            "map": "(oe)(œ)",
            "replace": 1
        },
```

**Comment by Questionsdenombres** [comment]
Thanks:

I tried to replace my local `....vscode\extensions\streetsidesoftware.code-spell-checker-french-0.2.4\node_modules\@cspell\dict-fr-fr\cspell-ext.json` with this:

```json
{
    "id": "fr-fr",
    "name": "French Dictionary (France)",
    "description": "French Dictionary (France)",
    "dictionaryDefinitions": [
        {
            "name": "fr-fr",
            "path": "./fr-fr.trie.gz",
            "description": "French Dictionary (France)"
            "dictionaryInformation": {
                "locale": "fr-FR",
                "alphabet": "a-zA-Zëqïéèöêüçàûîñäô",
                "suggestionEditCosts": [
                    {
                        "map": "(oe)(œ)",
                        "replace": 1
                    }
                ]
            }
        }
    ],
    "dictionaries": [],
    "languageSettings": [
        {
            "languageId": "*",
            "locale": "fr,fr_FR",
            "caseSensitive": true,
            "includeRegExpList": [],
            "patterns": [],
            "dictionaries": ["fr-fr"],
            "dictionaryDefinitions": []
        }
    ]
}

As a result, no french word was recognized anymore after starting again VSCode. So I went back.
Nevermind.

**Comment by Jason3S** [comment]
@Questionsdenombres,

There was is bug in the `.json` file:
```json
            "description": "French Dictionary (France)"
            "dictionaryInformation": {
```

needs a `,`
```json
            "description": "French Dictionary (France)",
            "dictionaryInformation": {
```

**Comment by Jason3S** [comment]
@Questionsdenombres,

Looks like it will need a bit more work for it to be successful. I tried it out, it still doesn't give it as a result. :-(

**Comment by Questionsdenombres** [comment]
Yes this solves the cspell VScode restart behavior, but it doesn't solve the initial request (see the image where "nœud" is not a proposed spell fix). Even if working it would probably be overwritten by the next "code-spell-checker-french" extension upgrade. Don't worry. 
![image](https://user-images.githubusercontent.com/47284986/214909623-d3557b49-9151-488d-af99-04cfb1d85b36.png)
