### ISSUE TITLE
Add double-a variants to Danish dictionary

### ISSUE THREAD

**Issue by esetnik** [streetsidesoftware/cspell-dicts#1842]
An example is `Lejemaal` which should be treated as a valid spelling of `Lejemål`

https://www.britishcouncil.org/voices-magazine/spelling-pronunciation-danish#:~:text='%C3%85'%20is%20the%20youngest%3B,could%20retain%20the%20double%2Da.

**Comment by Jason3S** [comment]
I just realized I hadn't responded.

The easiest way to fix this is to add those words to the dictionary. Since there are not a lot of places, that shouldn't be too hard.
