### ISSUE TITLE
How to add some missing in Linux enviroment?

### ISSUE THREAD

**Issue by mhf-ir** [streetsidesoftware/cspell-dicts#189]
Which category i must update for add this following words:
it's almost used in ansible playbooks mark as invalid but it's list a such popular names.
```
        "ansible",
        "influxdb",
        "ipset",
        "nignx",
        "swappiness",
        "syslog",
        "systemctl",
        "systemd",
        "telegraf",
        "wireguard"
```

**Comment by nschonni** [comment]
I would guess https://github.com/streetsidesoftware/cspell-dicts/tree/master/packages/software-terms, but you've misspelled "nginx" as "ningx"

**Comment by mhf-ir** [comment]
PR: https://github.com/streetsidesoftware/cspell-dicts/pull/191

**Comment by Jason3S** [comment]
Thank you!

**Comment by Jason3S** [comment]
PR merged. Closing.
