### ISSUE TITLE
Missing Words

### ISSUE THREAD

**Issue by anthony0030** [streetsidesoftware/cspell-dicts#1897]
# Missing Words

## NPM
* flatpickr
* jarallax
* mapboxgl
* jsbundling
* muuri
* pagy
* esbuild
* mkcert

## CSS
* clig
* calt
* lnum
* tnum
* zindex

## Fonts
* ysabeau
* busorama

## Companies
* viber
* waze
* imgix
* moovit
* cdnjs
* hulu
* papaki

## Other
* imessage
* wacag
* utma
* utmc

**Comment by Jason3S** [comment]
@anthony0030,

Thank you for the suggestions. Pull Requests are welcome! You can easily add these words right from GitHub UI:

- [cspell-dicts/npm.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/npm/src/npm.txt)
- [cspell-dicts/css.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/css/src/css.txt)
- [cspell-dicts/fonts.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/fonts/fonts.txt)
- [cspell-dicts/companies.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/companies/src/companies.txt)

`__utma, __utmc, __utmb`, etc... might be best in `frontend` or `html`.

**Comment by anthony0030** [comment]
# Made Pull Requests

- [X] NPM
- [] CSS
- [] Fonts
- [] Companies
- [] Other

**Comment by anthony0030** [comment]
Hi @Jason3S !

I made pull requests for all the changes.
Thank you for reminding me about the edit on GitHub option.

Have a great day!

**Comment by anthony0030** [comment]
I actually only made the edits, I am making the pull requests now :)

- [] NPM
- [] CSS
- [X] Fonts
- [] Companies
- [] HTML
