### ISSUE TITLE
British spelling of software terms

### ISSUE THREAD

**Issue by NMinhNguyen** [streetsidesoftware/cspell-dicts#193]
Hey, I wanted to ask - what's the best way to add support for British variants of software terms such as `parameterise`, `serialise` etc.? I can see that the dictionary seems to only include the US spelling:

https://github.com/streetsidesoftware/cspell-dicts/blob/4afa7b1aec594f9489b169bc77959d94cd699954/packages/software-terms/softwareTerms.txt#L384-L385

**Comment by nschonni** [comment]
There is a en-GB dictionary over in https://github.com/streetsidesoftware/cspell-dicts/tree/master/packages/en_GB which might be the right place

**Comment by NMinhNguyen** [comment]
Yeah, I just wasn't sure if software terms belonged in it, or whether `en-GB` should mirror `en-US`, but happy to create a PR adding those terms there.

**Comment by Jason3S** [comment]
A pull request would be welcome! Please add them to en-GB.
