### ISSUE TITLE
Update Go dictionary (maybe)

### ISSUE THREAD

**Issue by AlekSi** [streetsidesoftware/cspell-dicts#1973]
Hi, I updated https://github.com/AlekSi/go-words/blob/main/go.txt for Go 1.20. Not sure if you still use it :)

**Comment by Jason3S** [comment]
@AlekSi,

I believe the word list used is here: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/golang/src/go.txt

At PR is most welcome!

**Comment by AlekSi** [comment]
Is it go.txt or https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/golang/src/legacy_terms.txt? Should I update just that file?

**Comment by Jason3S** [comment]
@AlekSi,

I think [go.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/golang/src/go.txt) is the right place.

**Comment by AlekSi** [comment]
Thank you!
