### ISSUE TITLE
Dictionary request: Clojure(Script)

### ISSUE THREAD

**Issue by sfertman** [streetsidesoftware/cspell-dicts#206]
Great extension for vscode! Would be great to add Clojure(script) support. Would be happy to lend a hand.

**Comment by Jason3S** [comment]
It would be wonderful if you can do a pull request.
See: [how-to-create-a-new-dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)

**Comment by Jason3S** [comment]
If you have any improvements to the process, please let me know.

**Comment by KieranRobson** [comment]
With **https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/clojure** I believe this issue could be closed.
