### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Fasani** [streetsidesoftware/cspell-dicts#209]
To help maintain this project you could do the following:

This dictionary is not editable in the GitHub UI any more:
https://github.com/streetsidesoftware/cspell-dicts/blob/master/packages/en_GB/wordsEnGb.txt

We could split the dictionary into 26 files and join them with a build script.
```
[a,b,c,d,e,f,g,h,I ...]
```

This would allow easier editing within the GitHub UI, people would not have to clone the project locally, they could edit direct, also editing such a large single file becomes difficult to open on slower machines/editors.

As some letters are more common than others you will eventually no longer be able to edit some files in the GitHub UI, in which case you could add extra files build an array like so:

```
[a, am, b, c, d, dm, e, ...]
```

Where `m` represents the middle of the alphabet so you split the `a` file into 2 parts. You can keep splitting letters to maintain editability in the GitHub UI thus allowing people to contribute more easily.

Thoughts?

**Comment by Jason3S** [comment]
Thank you for pointing this out. I hadn't realized it had become difficult to edit.
I might move it back towards using the Hunspell dictionary with an `additions.txt` file that can be easily edited.
