### ISSUE TITLE
[Question] Does it working with Unicode Character?

### ISSUE THREAD

**Issue by lysari** [streetsidesoftware/cspell-dicts#2124]
I'm a developer from Cambodia. I have use your plugin longtime.I have problem with unicode characters like Cambodia Word can't be spell. how can I solve it. sorry for my english. thank for reply to me.

**Comment by Jason3S** [comment]
@lysari,

Here are directions on how to create a dictionary: [How to Create a New Dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)

A Hunspell dictionary like the one here should work: https://software.sil.org/fieldworks/download/spelling-dictionaries/

**Comment by lysari** [comment]
@Jason3S Thank you for information.
