### ISSUE TITLE
Fix wrong suggestion in Greek CAPITALS words

### ISSUE THREAD

**Issue by georgiosgiatsidis** [streetsidesoftware/cspell-dicts#218]
In Greek, there is a single mark that shows where the stress goes. For example, let's take the word Αθηνά. You can see the accent mark over the last vowel. 

When words are written in CAPITALS, the stress should not be marked! So the word should be written like ΑΘΗΝΑ, not ΑΘΗΝΆ. The plugin suggest me to fix it with ΑΘΗΝΆ which is wrong, so every word written in CAPITALS is considered as misspelt!

**Comment by Jason3S** [comment]
Thank you. Excellent feedback.

**Comment by Jason3S** [comment]
This should be fixed.

**Comment by georgiosgiatsidis** [comment]
@Jason3S Great job!
