### ISSUE TITLE
Question: Defining self made dictionary

### ISSUE THREAD

**Issue by evenstensberg** [streetsidesoftware/cspell-dicts#2411]
Hi. Is it possible to create a dictionary preferably as an npm package and referencing this dictionary in the cspell configuration file?

**Comment by Jason3S** [comment]
@evenstensberg,

That is how all of the dictionaries work.

For example, to use the Scientific Terms dictionary:

1. Install the package

   ```sh
   npm install -D @cspell/dict-scientific-terms-us
   ```
2. Include it in the `cspell.json` config

   ```jsonc
   {
       // Tell CSpell about the dictionary
       "import": ["@cspell/dict-scientific-terms-us/cspell-ext.json"],
       // Enable the dictionary
       "dictionaries": ["scientific-terms-us"]
   }
   ```

Please take a look at the packages in the [dictionaries](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries) folder for examples.

**Comment by evenstensberg** [comment]
Awesome, thanks! I was a bit confused since all the dicts seemed to be scoped to `@cspell/**`
