### ISSUE TITLE
Unable to add dictionaries

### ISSUE THREAD

**Issue by Hairy-Lee** [streetsidesoftware/cspell-dicts#2413]
The following steps have been undertaken (within PowerShell v7.3.6 tho similar result in v5 and CMD):

npm i -g cspell@latest
npm i -g @cspell/dict-fr-fr
npm i -g @cspell/cspell-json-reporter
npm list -g

+-- @cspell/cspell-json-reporter@7.0.0
+-- @cspell/dict-fr-fr@2.2.2
+-- cspell@7.0.0
+-- npm@9.8.1

cspell link add @cspell\dict-fr-fr

Adding:
filename                                                | errors
C:\Users\UserProfile\@cspell\dict-fr-fr | Failed to read file.

Tried installing and adding `dict-nl-nl` to but get the same outcome.

Reference: https://www.npmjs.com/package/cspell

I assume this isnt expected behaviour and I shouldnt get an erro message when I add a dictionary?

**Comment by Hairy-Lee** [comment]
Please ignore its a \ / issue

**Comment by nilscox** [comment]
I'm seeing this too with `cspell@7`, but not with `cspell@6`. To reproduce:

```sh
npm install -g cspell @cspell/dict-fr-fr
cspell link add @cspell/dict-fr-fr
```

Output:

```
Adding:
filename            | errors
/@cspell/dict-fr-fr | Failed to read file.
```
