### ISSUE TITLE
[Bug]: word 【swiper】 is not included in the directory

### ISSUE THREAD

**Issue by yinsang** [streetsidesoftware/cspell-dicts#2755]

**Comment by Jason3S** [comment]
I'm ok if someone wants to add it to the English shared words.

Just note: It is a very rare word, [Google N-Grams swiper](https://books.google.com/ngrams/graph?content=swiper%2Cunclick&year_start=2012&year_end=2019&corpus=en-2019&smoothing=0).

**Comment by yinsang** [comment]
But  it's very normal in Front-end project.

**Comment by Jason3S** [comment]
It is easy to add, just edit this file: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_shared/src/shared-additional-words.txt

and add it to the end.
