### ISSUE TITLE
Add new word "stylelint"

### ISSUE THREAD

**Issue by TheElegantCoding** [streetsidesoftware/cspell-dicts#2763]
[stylelint](https://stylelint.io) and Stylelint is a library well known for linting css this should not be an error

example of use in vscode settings

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/70770072/8744873e-41e1-4248-9768-4b4959740eaa)

**Comment by Jason3S** [comment]
@TheElegantCoding,

Pull Requests are welcome. Please add it here: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/npm/src/npm.txt

**Comment by albertothedev** [comment]
Isn't this word already present? It shows up in @Jason3S's [link](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/npm/src/npm.txt?rgh-link-date=2023-12-02T08%3A28%3A17Z) in line 642 and seems to have been added [in this commit](https://github.com/streetsidesoftware/cspell-dicts/commit/d6c26652e2d4200868f7ddf817a057f8e3625463#diff-37434eed74d122129e54ca41e4046d6e26f67d2ca3e243649aeef18cfbb5df86).

**Comment by Jason3S** [comment]
@albertothedev,

It is possible that the version of the dictionary shipped with the VSCode extension is out-of-date.

**Comment by TheElegantCoding** [comment]
still out of date in 6 mouths ?

**Comment by Jason3S** [comment]
> still out of date in 6 mouths ?

It is available in the v4 prerelease: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
