### ISSUE TITLE
How can I test my dictionary?

### ISSUE THREAD

**Issue by ndac-todoroki** [streetsidesoftware/cspell-dicts#28]
Thanks for the great plugin. I wanted to add support for Elixir, so I tried creating a dictionary myself.
https://github.com/ndac-todoroki/cspell-dicts/tree/add-elixir

While I tried to follow the instructions written in the README, several things didn't go straghtwards.

#### 1. https://github.com/Jason3S/cspell-dicts#running-the-generator
  - > In the cspell-dicts repository root.
  - This failed when performing "run build"

```
I'm all done. Running npm install for you to install the required dependencies.If this fails, try running the command yourself.


npm notice created a lockfile as package-lock.json. You should commit this file.
added 38 packages from 21 contributors and audited 94 packages in 6.291s
found 0 vulnerabilities


> cspell-dict-test@1.0.0 prepublishOnly /home/todoroki/git/cspell-dicts/test
> cp ../../util/* .

cp: '../../util/*' を stat できません: そのようなファイルやディレクトリはありません
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cspell-dict-test@1.0.0 prepublishOnly: `cp ../../util/* .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cspell-dict-test@1.0.0 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/todoroki/.npm/_logs/2018-06-21T08_23_37_391Z-debug.log
```

I think this should be run under `packages` (when I did it it went well)

#### 2. https://github.com/Jason3S/cspell-dicts#smoke-test

- I could run these commands
- I am not sure how to check it.

I created an example elixir script and opened it, but the spell checker claimed wrong spellings. I'm not sure whether my smoke-test setups have failed, or, my dictionary files are wrongly configured and thus not working.

It'll be great if you can support me with these two points.

Thanks in advance,
Todoroki

**Comment by Jason3S** [comment]
I fixed the generator and updated the libraries, so it creates the dictionary in the correct location.

I just went through the steps of generating a dictionary. It seems to be working.

The question is how to tell if your dictionary is working.

If you are running VS Code: 
* run the link step
* restart VS Code.
* in VS Code: `F1 Show Spell Checker Configuration Info`

The Dictionary tab should show your dictionary:
![image](https://user-images.githubusercontent.com/3740137/41809263-e86e5c24-76ea-11e8-9a55-d627d5a61cae.png)

If it is listed, but is not in use, then it is having trouble matching against the file type or the file type is not turned on for spell checking.

![image](https://user-images.githubusercontent.com/3740137/41809285-4a9d297a-76eb-11e8-8e84-21a9ac09eda1.png)

**Comment by ndac-todoroki** [comment]
Ah okay, I needed to restart VS Code! I haven't tried that. I restarted and is working well! Thanks.

**Comment by ndac-todoroki** [comment]
I tried that but seems not working... words included in the dictionary gets highlighted. 
Although, when I link -> restart vscode, in the actual files those words won't be highlighted. (`cspell` still highlights words as wrong.)

**Comment by Jason3S** [comment]
There was a bug in cspell 3.1.0, that may have caused issues. Can you update to cspell 3.1.1 and try using the command line again?

That should be the easiest way to test out a file.

**Comment by Jason3S** [comment]
I'm going to close this unless there is something more to do.
