### ISSUE TITLE
Where's Vue dictionary?

### ISSUE THREAD

**Issue by ErickPetru** [streetsidesoftware/cspell-dicts#291]
Vue Single-File Components (`.vue`) are well mapped by HTML dictionary. But some words used in its component instance API are considered "wrong" during spell checking, like `mixins`. I really would like to send a pull request adding this words, but... Where is the Vue dictionary?

**Comment by KieranRobson** [comment]
With https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/vue I think this issue could be closed.
