### ISSUE TITLE
`ocurred` shouldn't be in the dictionary

### ISSUE THREAD

**Issue by svrnm** [streetsidesoftware/cspell-dicts#2940]
We have been wondering (see https://github.com/open-telemetry/opentelemetry.io/pull/3825/files) why cspell was not catching `ocurred` automatically (since there is even a suggestion for an autofix), after doing some digging in your repos I found this:

https://github.com/streetsidesoftware/cspell-dicts/blob/dc56f6f63e68134c012456f796ef5f67d745ff06/dictionaries/en_US/src/en_US.txt#L13385

Can this be removed from that dictionary list?

**Comment by Jason3S** [comment]
@svrnm,

Thank you!

In case you did not know, the cspell `trace` command helps to find words.
```sh
cspell trace ocurred
``` 

<img width="751" alt="image" src="https://github.com/streetsidesoftware/cspell-dicts/assets/3740137/d6086532-04e6-4986-bed8-9ebbfd595110">

**Comment by svrnm** [comment]
thanks for fixing this so swiftly, @Jason3S! And also thank you for sharing the tip with the tracing, highly appreciated :-)

**Comment by geekley** [comment]
@Jason3S I'm still getting this on v4.0.45 in VSCode.
Trace shows it's coming from `cpp`. Is there a valid reason for C++ specifically?
I couldn't find this word in this repo's code...?

**Comment by Jason3S** [comment]
@geekley 
Would you open a new issue?
