### ISSUE TITLE
Julialang support

### ISSUE THREAD

**Issue by theogf** [streetsidesoftware/cspell-dicts#3036]
Hello!

It would be great to add support for the [Julia](https://julialang.org/) programming language. If someone would give me indications I could make a PR?

**Comment by Jason3S** [comment]
@theogf,

A PR would be welcome. Please see: [README: How to Create a New Dictionary](https://github.com/streetsidesoftware/cspell-dicts/blob/main/README.md#how-to-create-a-new-dictionary)
