### ISSUE TITLE
Ancient Greek dictionnary

### ISSUE THREAD

**Issue by juliaanvaneijndt** [streetsidesoftware/cspell-dicts#3062]
Would you consider making an Ancient greek dictionnary available for VSCode ? There is one in Hunspell format ([hunspell-ancient-greek](https://github.com/mrakia/hunspell-ancient-greek)). I tried to build a cspell dictionnary from it with generator-cspell-dicts but couldn't get it to work. Would be very useful and much appreciated!

**Comment by Jason3S** [comment]
@juliaanvaneijndt,

I have added Ancient Greek. Would you be able to provide a few links to some sample that can be used for testing?

Kind Regards,
Jason

**Comment by juliaanvaneijndt** [comment]
Great, thanks for doing it so quickly! For the tests, you can look [here](http://data.perseus.org/texts/urn:cts:greekLit:tlg0013.tlg004.perseus-grc1) or at any [Perseus](http://www.perseus.tufts.edu/hopper/collection?collection=Perseus%3Acorpus%3Aperseus%2CGreek%20Texts) text. Thanks again!

**Comment by Jason3S** [comment]
@juliaanvaneijndt,

Thank you.

The new extension can be found here: [Ancient Greek - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-ancient-greek)

**Comment by juliaanvaneijndt** [comment]
Thanks a lot, @Jason3S ! I've just tested it and it works perfectly.
