### ISSUE TITLE
MediaRecorder has dataavailable and ondataavailable

### ISSUE THREAD

**Issue by ADTC** [streetsidesoftware/cspell-dicts#3071]
See: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/dataavailable_event

Would be good to add these, but I'm not sure where.

**Comment by nschonni** [comment]
Probably in https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/typescript/src/typescript.txt

**Comment by Jason3S** [comment]
@nschonni, Thank you for the suggestion. 

@ADTC, I think [fullstack dictionary](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/fullstack/src/fullstack.txt) would be a better place.

**Comment by nschonni** [comment]
Fair enough, but it's a JavaScript API, and I think the TypeScript is still the alias for the JavaScript dictionary

**Comment by Jason3S** [comment]
> Fair enough, but it's a JavaScript API, and I think the TypeScript is still the alias for the JavaScript dictionary

You make a good point, I was basing my choice on the fact that it is a Web API. In any case, I am fine with either or both locations.
