### ISSUE TITLE
Persistance vs Persistence

### ISSUE THREAD

**Issue by bdovaz** [streetsidesoftware/cspell-dicts#3111]
en_US

https://github.com/streetsidesoftware/cspell-dicts/blob/d5ee05dfa61e68f8703db822ca9d074a4625d945/dictionaries/en_US/src/en_US.txt#L14368

en_GB

https://github.com/streetsidesoftware/cspell-dicts/blob/d5ee05dfa61e68f8703db822ca9d074a4625d945/dictionaries/en_GB/src/wordsEnGb.txt#L84390

https://dictionary.cambridge.org/spellcheck/english/?q=persistance

![image](https://github.com/streetsidesoftware/cspell-dicts/assets/950602/9a92c598-6b07-4ec3-bdda-b72913fcb0ad)

**Comment by Jason3S** [comment]
@bdovaz,

Thank you!

**Comment by Jason3S** [comment]
@bdovaz,

Thank you. If you see more of these, a PR is most welcome.

Kind regards
