### ISSUE TITLE
Suggestion for dependabot

### ISSUE THREAD

**Issue by ccoVeille** [streetsidesoftware/cspell-dicts#3351]
May I suggest you to use the groups feature in dependabot?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

This could reduce the number of PRs

**Comment by Jason3S** [comment]
Done. Thank you for the heads up. The last time I looked (I has been a long time), it wasn't possible.

https://github.com/streetsidesoftware/cspell-dicts/blob/6d49df9d167cdb09a9bbc70f916379e6cc2837b5/.github/dependabot.yaml#L12-L16

**Comment by ccoVeille** [comment]
Yes, only renovate not could, until last year
