### ISSUE TITLE
dict-people-names is not installable via npm

### ISSUE THREAD

**Issue by arkid15r** [streetsidesoftware/cspell-dicts#3352]
I might be missing something however it seems the recently created `dict-people-names` dictionary isn't available.

When I run `npm install @cspell/dict-people-names` I get

```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@cspell%2fdict-people-names - Not found
npm error 404
npm error 404  '@cspell/dict-people-names@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
```

Could you shed some light on this?

Thank you!

**Comment by Jason3S** [comment]
I have published it yet. I can do it tomorrow.

**Comment by arkid15r** [comment]
Thanks for publishing it!
