### ISSUE TITLE
HTML color names should probably all be known words

### ISSUE THREAD

**Issue by asktree** [streetsidesoftware/cspell-dicts#343]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/12001874/103699253-4ce1ed80-4f68-11eb-9b62-d8baa1dc4b30.png)
cSpell is angry about this, but it's an HTML color name. So it probably appears in many codebases and is not a typo.

**Describe the solution you'd like**
Add the HTML color name to the default dictionary. https://www.w3schools.com/colors/colors_names.asp
There may be an appropriate cSpell dictionary out there already, but I couldn't find it in the dictionaries repo. 

**Describe alternatives you've considered**
- Writing `"DarkSlateBlue"` in the code. Nobody does that though :-(
- Just adding it to my personal dictionary and shutting up
- Looking harder for a cSpell frontend dictionary.

**Comment by Jason3S** [comment]
Please add them to [dictionaries/html/html.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/master/dictionaries/html/html.txt)

**Comment by Jason3S** [comment]
The colors were add by @asktree
