### ISSUE TITLE
Support: Macedonian

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-dicts#3471]
Dear Street Side Software,
I love the Visual Studio Code extension, Code Spell Checker. I just wish that you would add the Macedonian 🇲🇰 language to be available.
Thank you in advance, David B., your loyal customer.

**Comment by Boshkovski-David** [comment]
@Jason3S 
Can we officially close this issue?😁

**Comment by Jason3S** [comment]
@Boshkovski-David,

Yes! Thank you.

**Comment by Jason3S** [comment]
PR: #3807

**Comment by Jason3S** [comment]
The extension is found here: [Macedonian - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-macedonian)

**Comment by Boshkovski-David** [comment]
Amazing thanks
