### ISSUE TITLE
Missing dictionary words related to technology

### ISSUE THREAD

**Issue by Poikilos** [streetsidesoftware/cspell-dicts#3472]
Dictionary words not in the spelling dictionary:
- [x] redetect
- [x] redetected
- [x] redetection
- [x] preinstall
- [x] preinstalled
- [x] backport(s)
- [x] backported
- [x] backporting
- [x] traceback(s)

**Comment by Jason3S** [comment]
@Poikilos,

Thank you.

If you could, please add the words to the end of this list: [dictionaries/software-terms/src/coding-terms.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/coding-terms.txt). It can be done from the GitHub UI using the edit button.

Kind regards,
Jason
