### ISSUE TITLE
upsert

### ISSUE THREAD

**Issue by mfulton26** [streetsidesoftware/cspell-dicts#3476]
I see that upsert is listed but only for specific software contexts. Can this word be added as a general software term? I feel like its applications are appropriate in any software context where an insert or update is being done.

- C++
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/cpp/dict/cpp-legacy.txt#L6682
- Full Stack
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/fullstack/dict/fullstack.txt#L452
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/fullstack/src/fullstack.txt#L445
- PHP
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/php/dict/php.txt#L3526
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/php/src/allowed-terms.txt#L395
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/php/src/php-functions.txt#L4670
- Python
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/python/dict/python-common.txt#L727
  - https://github.com/streetsidesoftware/cspell-dicts/blob/09814121cae3eb56be89196f270569bfd1a3ec3c/dictionaries/python/src/common/extra.txt#L724

**Comment by Jason3S** [comment]
@mfulton26,

Thank you. I agree it is a common coding term.


If you could, please add it to the end of this list: [dictionaries/software-terms/src/coding-terms.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/coding-terms.txt). It can be done from the GitHub UI using the edit button.

A trick to find a word in the dictionaries is to use the `trace` command:

```
cspell trace upsert
```

Kind regards,
Jason
