### ISSUE TITLE
PowerShell should have Runspace and Runspaces added to dict

### ISSUE THREAD

**Issue by ThomasNieto** [streetsidesoftware/cspell-dicts#3540]

**Comment by Jason3S** [comment]
@ThomasNieto,

Thank you for raising the issue.

Please consider making a PR to add them to the end of [dictionaries/powershell/src/powershell.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/powershell/src/powershell.txt). It is possible to edit the file in the GitHub UI, there is no need download the repository.
