### ISSUE TITLE
[PowerShell] Missing word in dictionary for operator `-isnot`

### ISSUE THREAD

**Issue by thakyZ** [streetsidesoftware/cspell-dicts#3577]
I found out that the operator for PowerShell scripts labeled `-isnot` is not included in the dictionary for PowerShell.

**Comment by Jason3S** [comment]
@thakyZ,

Thank you.

It is pretty easy to add, just add `-isnot` to this file: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/powershell/src/powershell.txt and make a PR.
It can be done in the online editor.

Kind regards,
Jason

**Comment by Jason3S** [comment]
@thakyZ,

I just realized that `isnot` was already in the dictionary. Do you have an example where it was an issue?

**Comment by thakyZ** [comment]
Yes, I do have an example and it is an issue in this code block:
```powershell
If ($Char -isnot [char]) {
    Throw [Exception]::new('For whatever reason an item in the string property -ToRemove is not type of [System.Char]');
}
```
And I made sure that the settings for `cSpell.dictionaries` in the file `.vscode/settings.json` contains `powershell`.

**Comment by Jason3S** [comment]
Please try out the v4 preview version. It has an updated dictionary. The v3 dictionaries are very old.
