### ISSUE TITLE
Add haptic/s

### ISSUE THREAD

**Issue by rbalet** [streetsidesoftware/cspell-dicts#3655]
## Description
`Haptic/s` is a common word used with [app development](https://capacitorjs.com/docs/apis/haptics)

But it is also an [english word](https://www.merriam-webster.com/dictionary/haptic).

Can someone point me out in which library I should add this name ?

**Comment by Jason3S** [comment]
It seems to be missing from the US English dictionary. But, it is a general English word.

Please add it to: https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_shared/src/shared-additional-words.txt

**Comment by rbalet** [comment]
@Jason3S Thx, closing in favore of https://github.com/streetsidesoftware/cspell-dicts/pull/3659
