### ISSUE TITLE
Question about tags for Russian

### ISSUE THREAD

**Issue by ccoVeille** [streetsidesoftware/cspell-dicts#3673]
Why is there ru_ru, while other languages are pt-pt, ro-ro and so on?

![Screenshot_20241011_215902_GitHub.jpg](https://github.com/user-attachments/assets/8cd01cc3-acd2-47b7-8490-7d878ae29c5e)

**Comment by ccoVeille** [comment]
Same question for pl_pl

https://github.com/streetsidesoftware/cspell-dicts/releases/tag/%40cspell/dict-pl_pl%403.0.3

**Comment by ccoVeille** [comment]
Same question for en_us, while it's en-gb

https://github.com/streetsidesoftware/cspell-dicts/releases/tag/%40cspell/dict-en_us%404.3.24

![Screenshot_20241011_222217_GitHub.jpg](https://github.com/user-attachments/assets/b635b0d4-51c2-467e-a09c-c59d3f3934e2)

**Comment by Jason3S** [comment]
@ccoVeille,

There isn't a good reason other than historical. When each of the dictionaries was made, the name was based upon the source dictionary found. Since there wasn't a clear convention: `en-US` vs `en_US` vs `enUS`. It was a bit random which name was picked. Over time, most dictionaries started using the `-`.

**Comment by ccoVeille** [comment]
I assumed it was something like that, or a random error made in the last days.

Would it be difficult to fix the few with a pattern?

**Comment by ccoVeille** [comment]
Side remark, language abbreviations are supposed to be lower case and country ones to be uppercase

POSIX locales relies on the pt_PT format

https://en.m.wikipedia.org/wiki/Locale_(computer_software)

But it would lead to rename all packages. I'm not asking for it.

Also having underscore in packages names for country will lead to mix underscore and dash in the packages names, it would lead to confusion.

**Comment by Jason3S** [comment]
There isn't a clear choice. HTML `hreflang` is lowercase with dashes. See: https://developers.google.com/search/docs/specialty/international/localized-versions

**Comment by Jason3S** [comment]
The spellchecker accepts all three forms.

**Comment by Jason3S** [comment]
> Would it be difficult to fix the few with a pattern?
> 

It would require publishing two packages for compatibility reasons.

**Comment by ccoVeille** [comment]
> 
> > Would it be difficult to fix the few with a pattern?
> > 
> 
> It would require publishing two packages for compatibility reasons. 
> 
OK, indeed. Never minor, then
