### ISSUE TITLE
How long will it take for my changes to be reflected in vs code?

### ISSUE THREAD

**Issue by spotlesscoder** [streetsidesoftware/cspell-dicts#3693]
So I added `msgstr` and some other terms a few days ago and I think they have been released in the meantime

I started a brand new Github Codespace where the streetsidesoftware spell checker extension was installed by default because it is in my user profile.
As the codespace was brandnew, I would also expet the dictionaries used by the spellcheck extension to be up to date
But `msgstr` and other strings I added still show up as spelling mistakes which is very distracting

How long will it take for my changes to be reflected there?
Could this be speed up somehow?

**Comment by Jason3S** [comment]
@spotlesscoder,

Dictionaries do not automatically up in the extension. A new version needs to be released.

v4 of the extension will use any locally installed dictionaries use by `cspell`.

You can always add `msgstr` to your own dictionary, then they will be hidden.

**Comment by spotlesscoder** [comment]
Ok that makes sense

How often is the extension released?

**Comment by Jason3S** [comment]
The best way to keep the dictionaries up to date is to install [`cspell`](https://www.npmjs.com/package/cspell) into your repo.

v4 of the Extension will pick up the dictionaries found in `node_modules`.

v4 is still in `preview`, but it is basically done. It needs some documentation corrections and a few minor tweaks.

v4 is released about 1/mo.  I'm thinking about a better way to keep the dictionaries in sync in a non-node environment.

**Comment by spotlesscoder** [comment]
Thanks for the clarification :)

**Comment by Jason3S** [comment]
@spotlesscoder,

I have added a new companion extension to help keep the dictionaries up to date: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-cspell-bundled-dictionaries

This extension will get updated with the latest dictionaries.

**Comment by spotlesscoder** [comment]
Very nice :) will try it out as soon as I find the time :)
