### ISSUE TITLE
💡: Support .astro filetype

### ISSUE THREAD

**Issue by mattmischuk** [streetsidesoftware/cspell-dicts#3712]
### Problem

By default, cSpell does not have support for Astro files.

### Solution

By extending `javascript`, `html`, and `html-symbol-entities` it’s fairly straightforward to bring support.

https://gist.github.com/mattmischuk/d6cfe512b5a6408fe501e6c05a71b3b8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jason3S** [comment]
@mattmischuk,

You will need to add the following extension to get the latest dictionary: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-cspell-bundled-dictionaries

**Comment by mattmischuk** [comment]
@Jason3S you rock! Thanks!

**Comment by Jason3S** [comment]
@mattmischuk 
Did it work for you?

**Comment by mattmischuk** [comment]
@Jason3S it is working :)
