### ISSUE TITLE
leaderboard

### ISSUE THREAD

**Issue by mfulton26** [streetsidesoftware/cspell-dicts#3760]
I see that "leaderboard" is defined in some dictionaries (e.g. gaming terms) but isn't it an English word that should always be included when using the English language?

https://www.merriam-webster.com/dictionary/leaderboard

**Comment by Jason3S** [comment]
@mfulton26,

Sorry for taking so long. Yes, please add it to: [dictionaries/en_shared/src/shared-additional-words.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_shared/src/shared-additional-words.txt)
