### ISSUE TITLE
Savviness is a word

### ISSUE THREAD

**Issue by mfulton26** [streetsidesoftware/cspell-dicts#3839]
cSpell recognizes savvy, savvier, savviest, savvied, and savvying as words but not savviness.

**Comment by Jason3S** [comment]
@mfulton26,

Good point. Would you add it here: [dictionaries/en_shared/src/shared-additional-words.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/en_shared/src/shared-additional-words.txt)?

**Comment by mfulton26** [comment]
Added, for my own education, where is savvy defined in cspell-dicts? Is it loaded from somewhere at build time? I don't see it when searching the repo on GitHub.

**Comment by Jason3S** [comment]
The easiest way to find out which dictionary contains a word is to use the `trace` command:

<img width="842" alt="image" src="https://github.com/user-attachments/assets/09d789d1-9ec2-480a-82ab-adc6031d4566">

Once you know the dictionary, then it is about finding where it is defined.

It is in a few `.dic` files:

<img width="275" alt="image" src="https://github.com/user-attachments/assets/c54b0e21-532c-4872-83c9-88da5678bc4c">
