### ISSUE TITLE
Dictionary suggestion: Metasyntactic variables for programming

### ISSUE THREAD

**Issue by andyw8** [streetsidesoftware/cspell-dicts#3844]
https://en.wikipedia.org/wiki/Metasyntactic_variable

I think these don't belong in the main programming dictionary, as some organizations have a style decision not to use them.

Examples: foobar, foo, bar, baz, qux, quux

**Comment by Jason3S** [comment]
@andyw8,

Thank you. I'm ok if you want to add them to [coding-terms](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/coding-terms.txt). It is pretty easy for an organization to forbid them.

They can make a dictionary with each word starting with `!` to flag it.
