### ISSUE TITLE
Add allowlist, denylist

### ISSUE THREAD

**Issue by rdsedmundo** [streetsidesoftware/cspell-dicts#413]
Those are better terms for whitelist/blacklist.

Similarly as:
```
whitelist
whitelisted
whitelisting
whitelists
```

**Comment by Jason3S** [comment]
@rdsedmundo,

Great idea. Would you like to make a pull request. Software Terms is the ideal location.

Example pull request: #387

**Comment by rdsedmundo** [comment]
Sure, I'll do it. Thanks for pointing out the example.
