### ISSUE TITLE
Extended Python Dictionary

### ISSUE THREAD

**Issue by Rollcloud** [streetsidesoftware/cspell-dicts#423]
Please add this additional dictionary for common Python functions:

[python_extended.txt](https://github.com/streetsidesoftware/cspell-dicts/files/6489724/python_extended.txt)

Functions sourced from Python 3.8 string, math, itertools, set modules and pytest 6.2.4 using:
```
import string
for each in dir(string):
    print(each)
```
Private (`_*`), sunder (`_*_`), and dunder (`__*__`) functions were excluded from the list.

**Comment by Jason3S** [comment]
@Rollcloud,

Thank you for the suggestion.

Please feel free to do a pull request. Example Pull Request: #397 

It is fine to just add the words to [dictionaries/python/python.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/master/dictionaries/python/python.txt)

Thank you.

**Comment by Rollcloud** [comment]
Thanks very much for the helpful feedback @Jason3S.

Pull request submitted.

Regards.
