### ISSUE TITLE
VScode installation instructions

### ISSUE THREAD

**Issue by Rollcloud** [streetsidesoftware/cspell-dicts#424]
Please add the following instructions to the readme for additional clarity:

## VScode additional dictionary installation

1. Open Settings
2. Search for `cspell`
3. Under `Custom Folder Dictionaries`, click `Edit in settings.json`
4. Insert the following at the bottom of the file (respecting appropriate brackets, commas and indentation):
  ```
    "cSpell.dictionaries": [
        "dictionary_name"
    ],
    "cSpell.dictionaryDefinitions": [
        {
            "name": "dictionary_name",
            "path": "ABSOLUTE_PATH_TO/dictionary_name.txt"
        }
    ]
```
5. Save and close `settings.json` and Settings
6. The new dictionary should automatically load

**Comment by nschonni** [comment]
Probably more something for https://github.com/streetsidesoftware/vscode-spell-checker

**Comment by Rollcloud** [comment]
Thanks for the quick response :)
Yes that might be more appropriate, I see there are some similar instructions there already - I'll open an issue there instead.
Sorry for the noise.
