### ISSUE TITLE
Use of Medical Terms Dictionary Violates GPLv3.0

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/cspell-dicts#440]
The [medical terms dictionary](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/medicalterms) [cites](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/medicalterms/medicalterms-en.md) a [GPLv3.0](https://github.com/glutanimate/wordlist-medicalterms-en/blob/master/LICENSE) project as the source of its dictionary yet [relicenses it MIT](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/medicalterms/LICENSE). I am not a lawyer, but I think the MIT license is moot in this case since streetsidesoftware does not have the right to grant unconditional use to a dictionary it did not create. The MIT license serves only to misinform those who depend on the medical terms package (either directly or transitively) and are also (unwittingly) in violation of the upstream GPLv3.0. Either the MIT license should be replaced with a GPLv3.0 license, as required by the GPLv3.0 or an alternative medical terms dictionary with a more permissive license should be found.

**Comment by Jason3S** [comment]
Thank you for bringing this up. I'll look into it. It was and is NOT the intent to relicense the original work.

**Comment by Jason3S** [comment]
@Kurt-von-Laven,
Thank you for bringing this up. It has been fixed and published: [@cspell/dict-medicalterms - npm](https://www.npmjs.com/package/@cspell/dict-medicalterms)
