### ISSUE TITLE
Review Licenses for each of the dictionaries

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-dicts#441]
The Licenses need to be reviewed for each of the dictionaries that are built from 3rd party sources.

Related to #440 

## Links:
- [Creative Commons license - Wikipedia](https://en.wikipedia.org/wiki/Creative_Commons_license)
- [GNU Lesser General Public License - Wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)
- [GNU General Public License - Wikipedia](https://en.wikipedia.org/wiki/GNU_General_Public_License)
- [Apache License - Wikipedia](https://en.wikipedia.org/wiki/Apache_License)
- [BSD licenses - Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses)
- [MIT License - Wikipedia](https://en.wikipedia.org/wiki/MIT_License)
- [Affero General Public License - Wikipedia](https://en.wikipedia.org/wiki/Affero_General_Public_License)

## A few notes:

From [Top 10 Questions About the Apache License | Mend](https://www.mend.io/blog/top-10-apache-license-questions-answered/#:~:text=Is%20the%20Apache%20license%20copyleft):
> **Is the Apache license copyleft?**
No. The Apache 2.0 License is [permissive](https://www.mend.io/blog/top-open-source-licenses-explained/). It allows you to use, modify, and distribute the licensed software, including creating derivative works, without requiring those derivative works to be licensed under the same terms. You can release the modified parts of the code under any license you prefer.
>
>There are some obligations. You must release all the unmodified parts of the software under the same license (the Apache License), and you must include copyright and attribution notices, disclaiming warranties, and provide a copy of the license with any distribution of the software.

**Comment by KieranRobson** [comment]
Do you have some guidance on how we can help with this issue as #705 is coming close to being finished haha

**Comment by calvinballing** [comment]
I've started a spreadsheet that looks at the licenses here: https://docs.google.com/spreadsheets/d/1x1T_DRv3cyGEhlGyFtVm82MgPhNcUQz96RizURV79O8/edit#gid=0

**Comment by Jason3S** [comment]
@calvinballing,

Wow, that is impressive. You put a lot of work into that.

Thank you.

I believe GPL and LGPL are very close to each other. My understanding is that GPL is slightly stricter than LGPL (since LGPL is intended to be linked as a library).

I have been trying to have the dictionary license match the source license if there is one.

I'm not sure about CC0, I have not fully looked into it.

**Comment by calvinballing** [comment]
First attempted license update to see if I'm doing this right: https://github.com/streetsidesoftware/cspell-dicts/pull/2624/files

**Comment by calvinballing** [comment]
Started a draft PR here to work on more of the updates: https://github.com/streetsidesoftware/cspell-dicts/pull/2627

**Comment by Maxim-Mazurok** [comment]
Hi guys, I'd like to use [Spanish dict](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/es_ES) but it's under GPL3 currently so corporate policy won't let me install it. I checked that [source](https://github.com/titoBouzout/Dictionaries) doesn't have license, and [hunspell license](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/es_ES/src/hunspell/license) seems to allow a choice of GPL3, LGPL3 and MPL.
If we could list all 3 of them in package.json - that would help, or just choose LGPL3 which seems to allow usage in proprietary software without the need to make it open-source.
Thank you!

**Comment by Jason3S** [comment]
@calvinballing, @Ki-er,

I think the first pass is done! Thank you for the help. I'm going to close this. We can open a new issue if more work needs to be done!
