### ISSUE TITLE
In markdown, an italicized word with an apostrophe is marked as incorrect

### ISSUE THREAD

**Issue by nidrissi** [streetsidesoftware/cspell-dicts#451]
I use the French dictionary extension of cspell.

In markdown, sentences can be italicized by surrounding them with underscores, e.g. `I do _not_ like potatoes`. In English, words containing an apostrophe work fine and are not marked as incorrect, for example `I _won't_ do it`. But with the French dictionary, such words are marked as incorrect, so for example `_l'abeille_` is marked as incorrect even though `l'abeille` is correct.

**Comment by Kurt-von-Laven** [comment]
The same is true of custom and the medicalterms dictionaries regardless of whether the underscores are present. My instinct is that the same transformations should be applied to all dictionaries, but I could definitely imagine there being drawbacks I have not contemplated.

**Comment by Jason3S** [comment]
This should be fixed with cSpell 5.

A few things are needed to get the extension to work.

1. The new version of the VS Code Spell Checker needs to be released. (In progress)
2. The French dictionary needs to be rebuilt to take advantage of the cSpell 5 features.

**Comment by Jason3S** [comment]
I believe this is fixed.
