### ISSUE TITLE
Missing UK Scientific Dictionary?

### ISSUE THREAD

**Issue by tecosaur** [streetsidesoftware/cspell-dicts#51]
I'll keep this brief.

I notice you have this http://jpetrie.net/wp-content/uploads/custom_scientific_US.dic
But do not appear to have the UK version http://jpetrie.net/wp-content/uploads/custom_scientific_UK.dic

Thanks,

tecosaur

**Comment by Jason3S** [comment]
Great idea.
I'll try to add it when I have time. If you would like it sooner, please feel free to do a pull request.
