### ISSUE TITLE
[Need help] [question] Issues with zz and ss

### ISSUE THREAD

**Issue by frolovdev** [streetsidesoftware/cspell-dicts#535]
Hi there, thanks for the awesome work you do

Here's my config

```
language: en

allowCompoundWords: true
```

And here's my version of cspell (installation through npm)

```
"cspell": "^5.6.6",
``` 

I face next error with postfix `sss` words
```
authorisation
realised
authorise
categorisation
```

But as far as I know 's endings are allowed in US eng

So I looking for your help to understand is it real problem or not and do we have any options to suppress such errors

**Comment by Jason3S** [comment]
A few things that might help:

To check if a work exists in a dictionary:
```sh
npx cspell trace authorisations
```

The output is something like this:
![image](https://user-images.githubusercontent.com/3740137/128212337-4461e000-5193-49c3-b9ad-a03b55f39502.png)

By default, the `language: en` is English US. To use British English, you need: `language: en-GB`.

If you do not care if it is US English or British English, then `langauge: "en-US,en-GB"` will work.

**Comment by frolovdev** [comment]
@Jason3S thanks for the fast feedback. 

So as far as I see, sss allowed in en_GB and zzz allowed in en_US. Ok looks great and also I can add any amount of "languages" and it looks like it covers most of the cases

```
language:
  - en-gb
  - en_us
  - cpp
  - java
 ```

Anyway, thanks for the great work, mate. Keep rocking 👍

**Comment by Jason3S** [comment]
@frolovdev 
- `languages` is where you can specify which natural languages to use (assuming you have the dictionary installed).

```yaml
# Locale for Natural languages
language:
  - en-gb
  - en-us # English US
  - es # Spanish

# Use the following dictionaries in addition to the one based upon the filetype.
dictionaries:
  - cpp
  - java
  - html
```

The `cspell trace` command show the list of dictionary names.

---
Do you find `cspell` useful? Here are some ways you can support future development:
- Contribute to dictionaries: [How to Create a Dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)
- Helping answer questions and fix issues:
    - [Issues · cspell](https://github.com/streetsidesoftware/cspell/issues)
    - [Issues · VS Code Extension](https://github.com/streetsidesoftware/vscode-spell-checker/issues)
    - [Issues · cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts/issues)
- Become a [<img src="https://github.githubassets.com/images/modules/site/icons/funding_platforms/patreon.svg" width="16" height="16" alt="Patreon">Patreon!](https://patreon.com/streetsidesoftware)
