### ISSUE TITLE
Unknown word endforeach 

### ISSUE THREAD

**Issue by ProtocolLive** [streetsidesoftware/cspell-dicts#544]
The extension dont know the word endforeach for PHP

**Comment by Jason3S** [comment]
@ProtocolLive,

Please feel free to add them (endfor, endif, endforeach) to [cspell-dicts/php.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/php/php.txt) and make a pull request. It is possible to do this in GitHub.
