### ISSUE TITLE
Just my cSpell.userWords list (AU-EN)

### ISSUE THREAD

**Issue by publicarray** [streetsidesoftware/cspell-dicts#556]
```json
    "cSpell.userWords": [
        "Nameserver",
        "Probot",
        "bunnycdn",
        "chmod",
        "csrf",
        "entrypoint",
        "groupname",
        "initialisation",
        "libsqlite",
        "octokit",
        "organiser",
        "postgres",
        "postgresql",
        "shellcheck",
        "sqlite"
    ],
```

**Comment by calvinballing** [comment]
This request looks to be about adding these strings to the Australian English dictionary. Current status of these strings:

- `nameserver` is currently found in these dictionaries: `cpp-legacy`, `cpp`, `de_AT`, `de_CH`, `de_DE`, `php`, and `ro_RO`, while `NAMESERVER` is found in `win32`, and `Nameserver` is found in `de_AT`, `de_CH`, `de_DE`.
- `chmod` is currently found in these dictionaries: `cpp-legacy`, `cpp`, `docker-words`, `go`, `node`, `php`, `python`, `softwareTerms`, and  `win32` 
- `csrf` is currently found in these dictionaries: `django` and `softwareTerms`
- `entrypoint` is currently found in these dictionaries: `cpp-legacy`, `cpp`, `softwareTerms`, and  `win32`,
while `ENTRYPOINT` is found in `docker-words`, `entryPoint` is found in `java`, and `EntryPoint` is found in `python-lib`.
- `groupname` is currently found in these dictionaries: `cpp-legacy` and `cpp` while `GROUPNAME` is found in `win32`, `GroupName` is found in `go`, and `groupName` is found in `node`
- `initialisation` is currently found in these dictionaries: `cpp-legacy`, `cpp`, British and Australian English, and French
- `octokit` is currently found in these dictionaries: `ruby` and `softwareTerms`
- `organiser` is currently found in these dictionaries: British and Australian English, French, and Norwegian
- `postgres` is currently found in this dictionaries: `django`, while `Postgres` is found in `softwareTerms`
- `PostgreSQL` is currently found in these dictionaries: Catalan, `cpp`, `cpp-legacy`, Austrialian, Canadian, and US English, Dutch, Brazilian Portuguese, US Scientific terms, Romanian, and Public Licenses
- `shellcheck` is currently found in these dictionaries: Bash and Shell
- `sqlite` is currently found in these dictionaries: `cpp`, `cpp-legacy`, `php`, and `win32`, while `SQLite` is found in Catalan, `cpp`, Australian, Canadian, and US English, and Software Terms
 
These words are not found in any dictionaries currently:
- `Probot` 
- `bunnycdn`
-  `libsqlite`

**Comment by Jason3S** [comment]
@calvinballing,

Thank you for looking at these. It looks like most of them already have a place.

- `probot` and `bunnycdn` could be added to software services.
- `libsqlite` - is a library package - depends upon how it is used.

**Comment by calvinballing** [comment]
Let me know if it looks like these are in the right spot, and whether you want to add any more of the terms to additional dictionaries
