### ISSUE TITLE
Test Dictionaries for Duplicates

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/cspell-dicts#624]
By chance, I noticed "pow" and "pytest" each appear twice in a row in the python dictionary, which made me think it might be nice to automatically check all dictionaries for duplicates. I don't know if that could be implemented in a way that also tests custom dictionaries for duplicates or whether that would even be worthwhile.

**Comment by Jason3S** [comment]
Duplicates get removed when the dictionaries are built. So, it isn't a big issue if duplicates exist in the source word lists.

**Comment by Jason3S** [comment]
I'm going to close this for now.
