### ISSUE TITLE
Task: Upgrade dictionaries

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/cspell-dicts#705]
# Task Upgrade Dictionaries

`cspell-tools-cli` generates dictionary files supporting some of the features in CSpell 5 that are not in CSpell 4.

### Features

- Case and accent checking (strict vs loose).
- Complex terms like `Good4Business` or `AA_dont_blend` are kept as a single terms
   instead of being broken up into separate words.

## Helping out

- Choose your favorite dictionary and follow the steps below.
- Please, only one dictionary per PR.

## Steps for general lists and programming languages

1. Bump the `version` in `package.json` to the next major version since we do NOT want to include the change in a CSpell 4 installation.
2. `package.json` in `scripts` change `cspell-tools` to `cspell-tools-cli`
    - Add `--split` if the source file contains spaces.
       This is important for dictionaries like the `companies` dictionary.
    - Add `--keep-raw-case` to programming language dictionaries. This option tells the tool to NOT generate
       lower case versions of each entry. In most cases, leaving this option off is ok.
3. run `pnpm run build` to build the dictionary.
4. run `pnpm run test` to make sure it has worked.

## Steps for Natural languages

Please take a look at [German `package.json`](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/de_DE/package.json) as an example.

1. Bump the `version` in `package.json` to the next major version since we do NOT want to include the change in a CSpell 4 installation.
2. `package.json` in `scripts` change `cspell-tools` to `cspell-tools-cli compile --trie3 -x compound ...`
    - Add `--trie3` - tells it to use the latest `trie` file format for optimal storage.
    - Add `-x compound` tells it to support the `Hunspell` compounds.
3. run `pnpm run build` to build the dictionary - this might take a _**long**_ time.
4. run `pnpm run test` to make sure it has worked.

## Dictionaries

Command Use to generate table:

```sh
find -s ./dictionaries -name "package.json" -depth 2 \
-exec jq -r "\"\
| \\(.scripts | @json | contains(\"cspell-tools \") | if . then \"🔲\" else \"✅\" end) \
| \\(.name) | \\(.version) | \\(.scripts | @json | contains(\"cspell-tools \") \
| if . then \"cspell-tools\" else \"cspell-tools-cli\" end) \
|\"" {} \; | pbcopy
```

| Done | package                             | version | tool             |
| ---- | ----------------------------------- | ------- | ---------------- |
| ✅ | @cspell/dict-ada | 4.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-al | 1.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-ar | 1.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-aws | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-bash | 4.1.1 | cspell-tools-cli |
| ✅ | @cspell/dict-bg-bg | 3.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-ca | 3.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-city-names-finland | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-clojure | 2.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-companies | 3.0.21 | cspell-tools-cli |
| ✅ | @cspell/dict-cpp | 5.0.4 | cspell-tools-cli |
| ✅ | @cspell/dict-cryptocurrencies | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-cs-cz | 3.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-csharp | 4.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-css | 4.0.7 | cspell-tools-cli |
| ✅ | @cspell/dict-da-dk | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-dart | 2.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-data-science | 1.0.11 | cspell-tools-cli |
| ✅ | @cspell/dict-de-at | 1.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-de-ch | 1.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-de-de | 3.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-django | 4.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-docker | 1.1.7 | cspell-tools-cli |
| ✅ | @cspell/dict-dotnet | 5.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-el | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-elixir | 4.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-en-common-misspellings | 1.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-en-au | 1.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-en-ca | 1.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-en-gb | 4.1.21 | cspell-tools-cli |
| ✅ | @cspell/dict-en-gb-mit | 2.1.11 | cspell-tools-cli |
| ✅ | @cspell/dict-en_us | 4.3.7 | cspell-tools-cli |
| ✅ | @cspell/dict-en-shared | 1.0.5 | cspell-tools-cli |
| ✅ | @cspell/dict-eo | 3.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-es-es | 2.2.6 | cspell-tools-cli |
| ✅ | @cspell/dict-et-ee | 2.0.9 | cspell-tools-cli |
| ✅ | @cspell/dict-eu | 1.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-fa-ir | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-filetypes | 3.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-fonts | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-fr-fr | 2.2.2 | cspell-tools-cli |
| ✅ | @cspell/dict-fr-reforme | 2.2.2 | cspell-tools-cli |
| ✅ | @cspell/dict-fsharp | 1.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-fullstack | 3.1.5 | cspell-tools-cli |
| ✅ | @cspell/dict-gaming-terms | 1.0.4 | cspell-tools-cli |
| ✅ | @cspell/dict-git | 2.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-golang | 6.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-haskell | 4.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-he | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-hr-hr | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-html | 4.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-html-symbol-entities | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-it-it | 3.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-java | 5.0.5 | cspell-tools-cli |
| ✅ | @cspell/dict-k8s | 1.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-latex | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-lorem-ipsum | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-lt-lt | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-lua | 4.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-markdown | 2.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-medicalterms | 4.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-mnemonics | 3.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-monkeyc | 1.0.5 | cspell-tools-cli |
| ✅ | @cspell/dict-nb-no | 2.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-nl-nl | 2.2.9 | cspell-tools-cli |
| ✅ | @cspell/dict-node | 4.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-npm | 5.0.8 | cspell-tools-cli |
| ✅ | @cspell/dict-php | 4.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-pl_pl | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-powershell | 5.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-pt-br | 2.2.0 | cspell-tools-cli |
| ✅ | @cspell/dict-pt-pt | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-public-licenses | 2.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-python | 4.1.7 | cspell-tools-cli |
| ✅ | @cspell/dict-r | 2.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-redis | 1.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-ro-ro | 1.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-ru_ru | 2.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-ruby | 5.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-rust | 4.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-scala | 5.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-scientific-terms-us | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-shell | 1.0.3 | cspell-tools-cli |
| ✅ | @cspell/dict-sk-sk | 1.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-sl-si | 1.0.4 | cspell-tools-cli |
| ✅ | @cspell/dict-software-terms | 3.2.2 | cspell-tools-cli |
| ✅ | @cspell/dict-sql | 2.1.1 | cspell-tools-cli |
| ✅ | @cspell/dict-sr-cyrl | 1.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-sr-latn | 1.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-sv | 2.1.0 | cspell-tools-cli |
| ✅ | @cspell/dict-svelte | 1.0.2 | cspell-tools-cli |
| ✅ | @cspell/dict-swift | 2.0.1 | cspell-tools-cli |
| ✅ | @cspell/dict-tr-tr | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-typescript | 3.1.1 | cspell-tools-cli |
| ✅ | @cspell/dict-uk-ua | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-vi-vn | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-vue | 3.0.0 | cspell-tools-cli |
| ✅ | @cspell/dict-win32 | 2.0.1 | cspell-tools-cli |

**Comment by KieranRobson** [comment]
Could ths table be updated so we know whats left? Thanks!

**Comment by Jason3S** [comment]
@KieranRobson,

Thank you!
