### ISSUE TITLE
`npm install generator-cspell-dicts` fails with an `aoo-mozilla-en-dict` error

### ISSUE THREAD

**Issue by igor-krupenja** [streetsidesoftware/cspell-dicts#727]
Steps:
1. Following the README, run `yarn create-dictionary et_EE ~/Downloads/dict/utf/et_EE.dic`.
2. Output says that you have to run `npm install generator-cspell-dicts` first.
3. When running this command I get the following error:

```log
npm WARN tarball tarball data for aoo-mozilla-en-dict@git+https://github.com/marcoagpinto/aoo-mozilla-en-dict.git (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for aoo-mozilla-en-dict@git+https://github.com/marcoagpinto/aoo-mozilla-en-dict.git (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/igor/.npm/_cacache/tmp/git-cloneddefKt/package.json
npm ERR! errno -2
[2021-10-30T12_13_08_878Z-debug.log](https://github.com/streetsidesoftware/cspell-dicts/files/7446467/2021-10-30T12_13_08_878Z-debug.log)
npm ERR! enoent ENOENT: no such file or directory, open '/Users/igor/.npm/_cacache/tmp/git-cloneddefKt/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/igor/.npm/_logs/2021-10-30T12_13_08_878Z-debug.log
```

Full logs: [2021-10-30T12_13_08_878Z-debug.log](https://github.com/streetsidesoftware/cspell-dicts/files/7446469/2021-10-30T12_13_08_878Z-debug.log)

Tried to Google but cannot seem to find anything relevant. Any ideas?

**Comment by Jason3S** [comment]
@igor-krupenja,

Please run `yarn` before trying to run `yarn create-dictionary`. Would you let me know if that works?

**Comment by Jason3S** [comment]
@igor-krupenja,

The dictionary already exists, so you don't need to create it again.

Please just replace the `.aff`, `.dic`, and any license files that came with it.

**Comment by igor-krupenja** [comment]
Was able to finally resolve this after uninstalling and reinstalling `yarn`. Anyway, I can just replace the files you mentioned. But don't I have to generate a `trie.gz` file as well?

**Comment by Jason3S** [comment]
If the names of the files didn't change, run `yarn build` in the `et-EE` directory. It might take a few minutes to finish.

**Comment by Jason3S** [comment]
@igor-krupenja,

Do you need help with this?

**Comment by Jason3S** [comment]
@igor-krupenja,

I updated the dictionary.
