### ISSUE TITLE
Add “Réforme 1990” French Dictionary

### ISSUE THREAD

**Issue by inwardmovement** [streetsidesoftware/cspell-dicts#85]
How can I force Cspell to use the french variant [Dictionnaire "Réforme 1990"](https://github.com/streetsidesoftware/cspell-dicts/blob/master/packages/fr_FR/French.txt#L67)?

**Comment by Jason3S** [comment]
The current French dictionary is the “CLASSIQUE”. To use the “Réforme 1990” a new dictionary would need to be created.

**Comment by inwardmovement** [comment]
Ok.
I am struggling to find the list of the words for this dictionary... If you know where I can find it tell me and I may add it to the project according to the [instructions](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary), in a PR.

In the meantime I've asked the *Académie française* if they could give me the list:

> Bonjour,
> 
> Comment puis-je me procurer la liste des mots de la version "Réformes 1990" du dictionnaire français, en format .txt ou .dic s'il vous plait ?
> 
> C'est pour implémenter la correction orthographique automatique (avec les dernières recommandations de l'Académie française) dans un logiciel de Microsoft utilisé par des dizaines de milliers de personnes dans le monde.
> 
> Bonne journée,
> Victor

I'll keep you posted.

**Comment by Jason3S** [comment]
I had gotten the original one from here: https://github.com/wooorm/dictionaries
But you might need to get the Réforme from here: https://grammalecte.net/documentation.php?prj=fr

**Comment by inwardmovement** [comment]
Thanks, I found the dic!
But I have an error while cloning my fork, can you help please? The cloned folder is empty.

```
git clone https://github.com/inwardmovement/cspell-dicts.git
Cloning into 'cspell-dicts'...
remote: Enumerating objects: 172, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 4653 (delta 105), reused 117 (delta 65), pack-reused 4481R
Receiving objects: 100% (4653/4653), 115.31 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (3647/3647), done.
BUG: refs/files-backend.c:2945: initial ref transaction called with existing refs
```

**Comment by Jason3S** [comment]
What version of `git` are you using? It is strange for it to crash.

**Comment by Jason3S** [comment]
To make changes, you should also use github `fork`.

![image](https://user-images.githubusercontent.com/3740137/62007417-6e249480-b14d-11e9-8119-2483c4df6da5.png)

Upper right corner of this repository.

Once you have added dictionary following: [How to create a new dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)

Create a pull request: [Creating a pull request from a fork - GitHub Help](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

**Comment by Jason3S** [comment]
Oops, forgive me if you already did a `fork`.

**Comment by inwardmovement** [comment]
> 
> 
> What version of `git` are you using? It is strange for it to crash.

The latest: `git version 2.22.0.windows.1`

**Comment by inwardmovement** [comment]
@Jason3S do you have any news on this?

**Comment by Jason3S** [comment]
I have no idea why `git` would crash. I can build the dictionary if necessary. Do you know where I would find it?

**Comment by inwardmovement** [comment]
[here](https://grammalecte.net/download.php?prj=fr), click *Dictionnaires Hunspell 6.4.1 05 avril 2019* and select `fr-reforme1990.aff` and `fr-reforme1990.dic`

**Comment by inwardmovement** [comment]
@Jason3S I deleted my fork and forked again, and now the cloning is working! I'll be able to build and PR I guess.

**Comment by inwardmovement** [comment]
@Jason3S so I tried to build, but it says that `cp` command does not exist. Then I tried in bash, and `cp` seems ok but now it's `cspell-tools` that is not recognized as a command:

> 'cspell-tools' n’est pas reconnu en tant que commande interne        
ou externe, un programme exécutable ou un fichier de commandes.

Are there requirements that are not mentioned in "How to create a new dictionary"?

**Comment by Jason3S** [comment]
Sorry about not getting back to you sooner.
You have to install `cspell-tools`.

`npm install -g cspell-tools`

That should fix it.

**Comment by inwardmovement** [comment]
No problem.
Ok thanks, here is the [PR](https://github.com/streetsidesoftware/cspell-dicts/pull/114), but I didn't manage to test the dictionary, maybe I didn't fill the YO fields the good way, I don't know... Can you have a look at it?

**Comment by Jason3S** [comment]
Thank you for the pull request.

**Comment by inwardmovement** [comment]
How can I enable `cspell-dict-fr-reforme@1.0.2` then?
I have a "preview" label on the extension, what does it mean and how can I get rid of it? Sorry I'm new to the "extension game"...

![image](https://user-images.githubusercontent.com/9438102/69493354-3ab10700-0eae-11ea-961f-4abfea8f2502.png)

**Comment by Jason3S** [comment]
No need to get rid of "Preview" is just means the extension is still under development.

**Comment by Jason3S** [comment]
Try disabling that dictionary extension and use:
![image](https://user-images.githubusercontent.com/3740137/69498831-72d73a80-0eec-11ea-8f2e-b2f19c53339d.png)

[French Réforme 90 - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french-reforme)

**Comment by Jason3S** [comment]
@inwardmovement See above.

**Comment by inwardmovement** [comment]
Works as expected, awesome, thank you!
