### ISSUE TITLE
French Elision missing.

### ISSUE THREAD

**Issue by CalvinRodo** [streetsidesoftware/cspell-dicts#93]
A lot of proper french words are being categorised as invalid spellings. 

Particularily anything that seems to be an elision
https://en.wikipedia.org/wiki/Elision_(French)

Some very common french words that are showing up as misspellings: 

c'est
d'un
d'une
j'aime

Basically any (Maybe not) word that is an elision is showing up as an error.

**Comment by Jason3S** [comment]
Strange. I'm not seeing this. Do you have an example file?

![image](https://user-images.githubusercontent.com/3740137/62208567-97d0fc00-b397-11e9-8e25-1b389d9c2cc1.png)

**Comment by CalvinRodo** [comment]
Looks like this has to do with the unique situation I'm in, I work for the Canadian government and am looking to integrate cspell into our CI Pipelines for checking spelling of markdown files. 

I'm checking multingual files that have Canadian English and French. 

Here is the .cspell.json that I'm currently using. 

https://github.com/canada-ca/aia-eia-js/blob/CI/.cspell.json

It looks like it was an issue with the order of the dictionaries. If I put fr as the language it works. 

Now I've got an issue with some Canadian Spellings of words but I'm sure I'll figure it out.

**Comment by edeleg** [comment]
Examples given are correct for me but pronominal verbs at first person are not:

Je **m'appelle**.
Tu **m'aimes**.
Il **m'**adore.
