### ISSUE TITLE
Create Arabic Language Dictionary 

### ISSUE THREAD

**Issue by AhmedElTabarani** [streetsidesoftware/cspell-dicts#941]
I will do this in PR, but not now.
I create this issue for me to remember it.

**Comment by WatheqAlshowaiter** [comment]
Thank you @AhmedElTabarani  for your support. 

I have asked Dr. [@linuxscout](https://github.com/linuxscout) about the dictionary and he gave me these two links: 
1- http://ayaspell.sourceforge.net/ (as he said if it is compatible with Hunspell)
2- https://sourceforge.net/projects/arabic-wordlist/ (if it only supports world list)

we can ask him for help if we need it.

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

sourceforge seems to be broken at the moment.

Here is another link: https://github.com/linuxscout/ayaspell

**Comment by Jason3S** [comment]
@WatheqAlshowaiter,

I can make the dictionary, but there is no way for me to tell if it is correct.

**Comment by WatheqAlshowaiter** [comment]
You can start and I will tell [@linuxscout](https://github.com/linuxscout), the creator of the dictionary, to elaborate. 
we will do our best to help as well.

**Comment by Jason3S** [comment]
fixed by #1293

**Comment by AhmedElTabarani** [comment]
@WatheqAlshowaiter you will continue and make the pr or i will do it?

**Comment by Jason3S** [comment]
@AhmedElTabarani,

I already published it: https://www.npmjs.com/package/@cspell/dict-ar

**Comment by WatheqAlshowaiter** [comment]
Thanks a lot @Jason3S. 🌹
@AhmedElTabarani I will do it. If I need help I will ask you.

**Comment by WatheqAlshowaiter** [comment]
@Jason3S 
I have this issue when I whant to push the code 
```
fatal: unable to access 'https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/': The requested URL returned error: 403
```

Do I need to make it as a fork?

**Comment by AhmedElTabarani** [comment]
Make it as a fork then Make a PR

**Comment by WatheqAlshowaiter** [comment]
I have done that 
https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/pull/336

**Comment by Jason3S** [comment]
@WatheqAlshowaiter  and @AhmedElTabarani,

It might be necessary to adjust the dictionary to improve the suggestions.

There was a discussion here: https://github.com/streetsidesoftware/cspell/issues/2249#issuecomment-1031165944 that might be related.

**Comment by AhmedElTabarani** [comment]
Hi @Jason3S, I tried to enable the Arabic Extension, but it's not working,
 - I install both the original code spell extension and the Arabic version 
- I click `f1` then `Show Spell Checker Configuration Info` then `I select the Arabic Language tab` 
- I make sure the settings and put `"cSpell.language": "en,ar"` into it  

But the Arabic checking not working, only the English is working.

**Comment by WatheqAlshowaiter** [comment]
Hi @Jason3S 
as you mentioned the link to improve the dictionary in this [link](https://github.com/streetsidesoftware/cspell/issues/2249#issuecomment-1031165944)

we have a problem in [Harakat in Arabic](https://github.com/streetsidesoftware/cspell/issues/2249#issuecomment-1031182816). They are considered complete letters. How we can ignore them?


![Screen Shot 2022-07-29 at 11 43 43](https://user-images.githubusercontent.com/24838274/181720877-3a19a87b-803a-4bf2-957e-c5d6a6c1955f.png)
