### ISSUE TITLE
upcase is a valid Elixir keyword

### ISSUE THREAD

**Issue by datafoo** [streetsidesoftware/cspell-dicts#950]
`upcase` is a valid Elixir keyword: https://hexdocs.pm/elixir/1.13.3/String.html#upcase/2

Yet, it is detected as "Unknown word" by `cspell 5.18.5`.

**Comment by Jason3S** [comment]
@datafoo,

Related to #949, #948

Please add them to https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/elixir/elixir.txt
