### ISSUE TITLE
Add common package names to exception list

### ISSUE THREAD

**Issue by bboysnick5** [streetsidesoftware/cspell-dicts#972]
I think this one must have been asked but I cannot find it. Can we add exceptions to common package names for example lxml for python and say boost for cpp if not already?

**Comment by Jason3S** [comment]
I suggest just adding the words to the respective dictionaries:
- [cspell-dicts/python.txt at main · streetsidesoftware/cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/python/python.txt)
- [cspell-dicts/cpp.txt at main · streetsidesoftware/cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/cpp/cpp.txt)

**Comment by bboysnick5** [comment]
Well sure but I think a more structured way for programming languages is reasonably better isn't it, for better scalability and more maintainable. Something like a layered structure say python dict[python-core, common packages, deep-learning/data-science], cpp dict[cpp-core, stl, common packeges, etc]. Something like that.

**Comment by Jason3S** [comment]
@bboysnick5,

I agree with you. It is not hard to divided the files into their categories. Please feel free to add more structure. 
[cspell-dicts/dictionaries/software-terms](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/software-terms) is a good example of a dictionary built from multiple source files.
