### ISSUE TITLE
en-US dictionary includes en-GB spelling

### ISSUE THREAD

**Issue by luke-underwood** [streetsidesoftware/cspell-dicts#979]
Hi! This plugin is awesome.

I noticed a few examples of British English being included in the US dictionary. Is this intentional?

- [colour*](https://github.com/streetsidesoftware/cspell-dicts/blob/c975f6495a93853619b38def8ae6d459c0b5eac0/dictionaries/en_US/src/en_US.txt#L3723-L3728)
- [analyse*](https://github.com/streetsidesoftware/cspell-dicts/blob/c975f6495a93853619b38def8ae6d459c0b5eac0/dictionaries/en_US/src/en_US.txt#L653-L655)
- [defence*](https://github.com/streetsidesoftware/cspell-dicts/blob/c975f6495a93853619b38def8ae6d459c0b5eac0/dictionaries/en_US/src/en_US.txt#L4742-L4743)

Our company language uses US English so I've excluded the GB dictionary using `"cSpell.dictionaries": [ "!wordsEnGb" ]` however some words like above are still marked as correct

**Comment by Jason3S** [comment]
@luke-underwood,

Looks like they made it into an old word list. 

Please feel free to make a Pull Request  to remove them.

In the meantime, you can make these word forbidden in your company dictionary by adding a `!` prefix.

```
!colour
!analyse
!defence
```
